In [42]:
import pandas as pd

In [2]:
#Series

In [3]:
sr = pd.Series(["Ahmad","Python","Class"],index=["*","=>","!"])

In [4]:
sr

*      Ahmad
=>    Python
!      Class
dtype: str

In [5]:
userData = {"name":["Ahmad","python","Class"],"age":[25,26,27]}

In [6]:
userData

{'name': ['Ahmad', 'python', 'Class'], 'age': [25, 26, 27]}

In [7]:
df = pd.DataFrame(userData)

In [8]:
df

     name  age
0   Ahmad   25
1  python   26
2   Class   27

In [9]:
df.to_csv("ClasFirstTable.csv")

In [43]:
dfItems = pd.read_excel("C:\\CurrentUnityProjects\\NavClassAdvancePython\\AdvancePythonClassRepo\\PandasTabularData\\VendorProducts.xlsx",sheet_name="Items")
dfCollections= pd.read_excel("C:\\CurrentUnityProjects\\NavClassAdvancePython\\AdvancePythonClassRepo\\PandasTabularData\\VendorProducts.xlsx",sheet_name="Collections")

In [11]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [12]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [13]:
print(type(dfItems))
print(type(dfItems["Secondary Description"]))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [14]:
#Name
#Price
#Brand
#Barcode

In [15]:
dfItems["Price"]

0         25,000د.ع
1        300,000د.ع
2         30,000د.ع
3             00د.ع
4         15,000د.ع
            ...
24697     16,500د.ع
24698     12,000د.ع
24699     10,500د.ع
24700     15,000د.ع
24701     22,500د.ع
Name: Price, Length: 24702, dtype: str

In [16]:
x =" 25,000د.ع"
25000

25000

In [17]:
dfItems.info()

<class 'pandas.DataFrame'>
RangeIndex: 24702 entries, 0 to 24701
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Picture                    24300 non-null  str
 1   Id                         24702 non-null  int64
 2   Name                       24702 non-null  str
 3   Secondary Name             24702 non-null  str
 4   Barcode                    22041 non-null  str
 5   Code                       21993 non-null  str
 6   Price                      24702 non-null  str
 7   Description                24645 non-null  str
 8   Secondary Description      24644 non-null  str
 9   Sub Description            24601 non-null  str
 10  Secondary Sub Description  4 non-null      str
 11  Menu                       24699 non-null  str
 12  Brand                      24699 non-null  str
 13  Secondary Brand            24696 non-null  str
 14  Has Collections            24702 non-null  str
dtypes: int64(1), str(14)
memory usage: 2.8 MB

In [18]:
dfItems.describe()

                  Id
count   24702.000000
mean   330583.440936
std     12701.598678
min    314991.000000
25%    321257.250000
50%    327496.500000
75%    334544.750000
max    390188.000000

In [19]:
dfItems.head()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No

In [20]:
dfItems.tail()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [21]:
dfItems.fillna("")

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,,,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [22]:
dfItems[["Name"]].fillna("")

                                                   Name
0                            زيت الشفاه بليجر 001، 5 مل
1                  عطر بلو دي شانيل لي اكسكلوسيف الجديد
2                 سيروم الشعر لفروة الرأس سيابوري 20 مل
3                        عطر جانيميد اودي بارفيوم 50 مل
4                   جل تصفيف الحواجب مع الببتيدات 15 مل
...                                                 ...
24697        معطر الشعر والجسم بالليمون والماتشا 150 مل
24698  معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل
24699         ماسكارا جلام اند دول تعزز نمو الرموش 8 مل
24700                        مست الجسم باشن فروت 150 مل
24701               ماسكارا فائقة الكثافة (1أسود) 15 مل

[24702 rows x 1 columns]

In [23]:
#Make a data Frame of UserName /  Age / Class
# Save file as userData.csv

In [24]:
UserDataDictionary = {"Name":["Ahmad","Python","Class"],"Age":[25,26,27],"Class":["A","B","C"]}

In [25]:
df = pd.DataFrame(UserDataDictionary)

In [26]:
df.to_csv("UserData.csv",index=False)

In [27]:
UserDF = pd.read_csv("UserData.csv")

In [28]:
UserDF

     Name  Age Class
0   Ahmad   25     A
1  Python   26     B
2   Class   27     C

In [29]:
currentrowNumber = len(UserDF["Name"])
UserDF.loc[currentrowNumber] = ["Ali","25","A"]

In [30]:
UserDF1 = UserDF

In [31]:
UserDF1.to_csv("UserData.csv",index=False)

In [32]:
UserDF1

     Name Age Class
0   Ahmad  25     A
1  Python  26     B
2   Class  27     C
3     Ali  25     A

In [33]:
# Create banking System
# Ask user to Create Account or Check or withDraw or deposit
# Use while true for this process
# Lets say user created account = 5000
# Dictionary Example = {"UserNames":[a,b,c,d,e],"Age":[1,2,3,4],"Balance":[1000,2000,3000,4000]
#Create a csv and store data in therep

In [34]:
"""
Create a Simple Banking System in Python that stores account data in a CSV file using the Pandas library. The program should be menu-driven and continuously run until the user chooses to exit. The CSV file should contain the columns AccountNumber, Name, and Balance. The program must support the following operations:
	1.	Create Account – Ask the user for account number, customer name, and initial balance, then store the record in the CSV file.
	2.	Deposit Money – Ask for account number and deposit amount, find the account, and increase the balance.
	3.	Withdraw Money – Ask for account number and withdrawal amount, check if the account has sufficient balance, and subtract the amount if possible. If not, display “Insufficient Balance.”
	4.	Check Balance – Ask for the account number and display the current balance of that account.
	5.	Exit – Terminate the program when the user selects this option.

The program should read data from the CSV file, update it when transactions occur, and save the updated data back to the file.
"""

'\nCreate a Simple Banking System in Python that stores account data in a CSV file using the Pandas library. The program should be menu-driven and continuously run until the user chooses to exit. The CSV file should contain the columns AccountNumber, Name, and Balance. The program must support the following operations:\n\t1.\tCreate Account – Ask the user for account number, customer name, and initial balance, then store the record in the CSV file.\n\t2.\tDeposit Money – Ask for account number and deposit amount, find the account, and increase the balance.\n\t3.\tWithdraw Money – Ask for account number and withdrawal amount, check if the account has sufficient balance, and subtract the amount if possible. If not, display “Insufficient Balance.”\n\t4.\tCheck Balance – Ask for the account number and display the current balance of that account.\n\t5.\tExit – Terminate the program when the user selects this option.\n\nThe program should read data from the CSV file, update it when transactions occur, and save the updated data back to the file.\n'

In [35]:
import random as rd
while True:
    choice = int(input("Enter 1 for account Opening \n Enter 2 for Balance Check \n Enter 3 for WithDrawl \n Enter 4 for Deposit: \n Enter 5 for Exit:"))
    if choice ==1:
        userDB = pd.read_csv("Bank.csv")
        userName = input("Enter User Name:")
        accNo = rd.randint(10000,99999)
        balance = 5000
        newUserDataList = [accNo,userName,balance]
        currentrowNumber = len(userDB["AccountNumber"])
        userDB.loc[currentrowNumber] = newUserDataList
        userDB.to_csv("Bank.csv",index=False)
        print("Account Created")
    elif choice ==2:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                print(f"Welcome {nm} \nYour Balance is {userDB['Balance'][i]}")

    elif choice ==3:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                amount2Wtihdraw = int(input("Enter Amount to Withdraw:"))
                userDB['Balance'][i] = userDB['Balance'][i] - amount2Wtihdraw
                # userDB['Balance'][i] = newBalance
                print(f"Welcome {nm} \nYour new Balance is {userDB['Balance'][i]}")
                userDB.to_csv("Bank.csv",index=False)
    elif choice ==4:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                amount2Wtihdraw = int(input("Enter Amount to Withdraw:"))
                userDB['Balance'][i] = userDB['Balance'][i] + amount2Wtihdraw
                # userDB['Balance'][i] = newBalance
                print(f"Welcome {nm} \nYour new Balance is {userDB['Balance'][i]}")
                userDB.to_csv("Bank.csv",index=False)
    elif choice ==5:
        print("Exiting")
        break

KeyboardInterrupt: Interrupted by user

In [151]:
userDictionary = {"AccountNumber":[10001],"FullName":["Ahmad"],"Balance":[5000]}
df = pd.DataFrame(userDictionary)
df

   AccountNumber FullName  Balance
0          10001    Ahmad     5000

In [152]:
df.to_csv("Bank.csv",index=False)

In [1]:
"""
user id = string
username = string
class = sstring
subjects = list


Student registration
Student information fetch
student information update
"""

'\nuser id = string\nusername = string\nclass = sstring\nsubjects = list\n\n\nStudent registration\nStudent information fetch\nstudent information update\n'

In [2]:
import pandas as pd

In [17]:
StudentAccountDictionary = {"StudentId":["10001","10002","10003"],"StudentName":["Ahmad","Ali","yth"],"StudentClass":["1","2","3"],"Subjects":[["Math","English","Science"],["Math","Chemistry","Science"],["islamicStudies","English","Physics"]]}

In [18]:
studentDF = pd.DataFrame(StudentAccountDictionary)

In [19]:
studentDF

  StudentId StudentName StudentClass                            Subjects
0     10001       Ahmad            1            [Math, English, Science]
1     10002         Ali            2          [Math, Chemistry, Science]
2     10003         yth            3  [islamicStudies, English, Physics]

In [20]:
studentDF.to_csv("StudentData.csv",index=False)

In [3]:
import random as r
while True:
    choice = input("Enter 1 for Student Registration \n Enter 2 for Student Information Fetch \n Enter 3 for Student Information Update \n Enter 4 for Exit:")
    if choice == "1":
        print("======Registering Student========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = r.randint(10000,99999)
        studentName = input("Enter Student Name:")
        studentClass = input("Enter Student Class:")
        subjects = ["Maths","English","Science"]
        currentrowNumber = len(studentDF["StudentId"])
        studentDF.loc[currentrowNumber] = [studentId,studentName,studentClass,subjects]
        studentDF.to_csv("StudentData.csv",index=False)

        print("======Registering Student========")

    elif choice =="2":
        print("======Student Information Fetch========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print(f"Student Name : {studentDF['StudentName'][i]}")
                print(f"Student Class : {studentDF['StudentClass'][i]}")
                print(f"Student Subjects : {studentDF['Subjects'][i]}")
        print("======Student Information Fetch========")
    elif choice =="3":
        print("======Student Information Update=======")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print("What do you want to update?")
                updateChoice = input("Enter 1 for Student Name \n Enter 2 for Student Class \n Enter 3 for Student Subjects:")
                if updateChoice == "1":
                    newStudentName = input("Enter New Student Name:")
                    studentDF['StudentName'][i] = newStudentName
                    print(f"Student Name Updated to {newStudentName}")
                elif updateChoice == "2":
                    newStudentClass = input("Enter New Student Class:")
                    studentDF['StudentClass'][i] = newStudentClass
                    print(f"Student Class Updated to {newStudentClass}")
                elif updateChoice == "3":
                    subjectsChoice = input("Do you want to add subjects or remove subjects? Enter 1 for Add \n Enter 2 for Remove:")
                    if subjectsChoice == "1":
                        newSubjects = input("Enter New Subjects:")
                        studentDF['Subjects'][i].append(newSubjects)
                        print(f"Student Subjects Updated to {studentDF['Subjects'][i]}")
                    if subjectsChoice == "2":
                        subjectsToRemove = input("Enter Subjects to Remove:")
                        studentDF['Subjects'][i].remove(subjectsToRemove)
        print("======Student Information Update=======")
    elif choice =="4":
        print("Exiting")
        break

======Registering Student========
======Registering Student========
Exiting

In [18]:
dfItems.loc(0)

                                       Secondary Name       Price
1                    Bleu De Chanel L'Exclusif Parfum  300,000د.ع
2                     Seapuri Scalpy Hair Serum 20 ml   30,000د.ع
3                                  Ganymede EDP 50 ml       00د.ع
4               Brow Styling Gel With Peptides 15 ml    15,000د.ع
5                             Limitless Mascara 10 ml   15,000د.ع
6                                  Eyebrow Serum 5 ml   18,000د.ع
7                               Evadamo Mascara 10 ml   15,000د.ع
8                        Argan Oil Conditioner 300 ml    7,750د.ع
9                       Argan Oil Conditioner 1000 ml   15,500د.ع
10  Professional 1500 W Hair Dryer With 7 Attachments   65,000د.ع

In [37]:
questionare=pd.read_csv("QuestionareDummy.csv")

In [38]:
questionare

,Question,Option A,Option B,Option C,Option D,Right Answer
0,Which programming language is known as the 'mo...,Python,C,Java,Assembly,B
1,What is the chemical symbol for Gold?,Gd,Ag,Au,Go,C
2,Which planet is known as the Red Planet?,Venus,Mars,Jupiter,Saturn,B
3,What does 'CPU' stand for?,Central Processing Unit,Control Programming Unit,Computer Personal Unit,Central Print Utility,A
4,Which ocean is the largest on Earth?,Atlantic Ocean,Indian Ocean,Arctic Ocean,Pacific Ocean,D
5,"In Python, which library is commonly used for ...",NumPy,Pandas,Matplotlib,PyQt,B
6,Who painted the Mona Lisa?,Vincent van Gogh,Pablo Picasso,Leonardo da Vinci,Claude Monet,C
7,What is the capital city of Japan?,Seoul,Beijing,Bangkok,Tokyo,D
8,Which component is responsible for long-term d...,RAM,CPU,HDD/SSD,GPU,C
9,What is the square root of 144?,10,12,14,16,B
10,Which gas do plants primarily absorb for photo...,Oxygen,Nitrogen,Carbon Dioxide,Hydrogen,C
11,"In Unity, which file extension is used for C# ...",.unity,.cpp,.js,.cs,D
12,What is the powerhouse of the cell?,Nucleus,Ribosome,Mitochondria,Cytoplasm,C
13,Which country is the largest by land area?,USA,China,Russia,Canada,C
14,What is the value of Pi rounded to two decimal...,3.12,3.14,3.16,3.18,B
15,Who is credited with inventing the World Wide ...,Steve Jobs,Bill Gates,Tim Berners-Lee,Elon Musk,C
16,Which element has the atomic number 1?,Helium,Oxygen,Hydrogen,Carbon,C
17,What is the currency of the United Kingdom?,Euro,Dollar,Pound Sterling,Yen,C
18,Which year did the Titanic sink?,1905,1912,1918,1924,B
19,"Which data structure follows the 'Last-In, Fir...",Queue,Array,Stack,Linked List,C
20,Which city is known as the 'Big Apple'?,Los Angeles,Chicago,Miami,New York City,D

In [41]:
# Read Questions from above CSV
#Prepare 5-10 questions for a quiz
# A user will come and enter his/her name and take the quiz.
# One user cannot take quiz twice
# Save user score in a different csv named as student score
# if a student fail any question game will be end instantly

In [45]:
import random as r
randomnumberList = []
for i in range(10):
    while True:
        random10Numbers = r.randint(0,21)
        if random10Numbers not in randomnumberList:
            randomnumberList.append(random10Numbers)
            break
        else:
            continue

In [46]:
randomnumberList

[0, 20, 7, 11, 17, 6, 18, 1, 13, 15]

In [24]:
import pandas as pd
import random as r
# _Read Questions from above CSV_
# _Prepare 5-10 questions for a quiz_
# A user will come and enter his/her name and take the quiz.
# One user cannot take quiz twice
# Save user score in a different csv named as student score
# if a student fail any question game will be end instantly

import random as r

In [25]:

questionare = pd.read_csv("QuestionareDummy.csv")

In [26]:
questionare

,Question,Option A,Option B,Option C,Option D,Right Answer
0,Which programming language is known as the 'mo...,Python,C,Java,Assembly,B
1,What is the chemical symbol for Gold?,Gd,Ag,Au,Go,C
2,Which planet is known as the Red Planet?,Venus,Mars,Jupiter,Saturn,B
3,What does 'CPU' stand for?,Central Processing Unit,Control Programming Unit,Computer Personal Unit,Central Print Utility,A
4,Which ocean is the largest on Earth?,Atlantic Ocean,Indian Ocean,Arctic Ocean,Pacific Ocean,D
5,"In Python, which library is commonly used for ...",NumPy,Pandas,Matplotlib,PyQt,B
6,Who painted the Mona Lisa?,Vincent van Gogh,Pablo Picasso,Leonardo da Vinci,Claude Monet,C
7,What is the capital city of Japan?,Seoul,Beijing,Bangkok,Tokyo,D
8,Which component is responsible for long-term d...,RAM,CPU,HDD/SSD,GPU,C
9,What is the square root of 144?,10,12,14,16,B
10,Which gas do plants primarily absorb for photo...,Oxygen,Nitrogen,Carbon Dioxide,Hydrogen,C
11,"In Unity, which file extension is used for C# ...",.unity,.cpp,.js,.cs,D
12,What is the powerhouse of the cell?,Nucleus,Ribosome,Mitochondria,Cytoplasm,C
13,Which country is the largest by land area?,USA,China,Russia,Canada,C
14,What is the value of Pi rounded to two decimal...,3.12,3.14,3.16,3.18,B
15,Who is credited with inventing the World Wide ...,Steve Jobs,Bill Gates,Tim Berners-Lee,Elon Musk,C
16,Which element has the atomic number 1?,Helium,Oxygen,Hydrogen,Carbon,C
17,What is the currency of the United Kingdom?,Euro,Dollar,Pound Sterling,Yen,C
18,Which year did the Titanic sink?,1905,1912,1918,1924,B
19,"Which data structure follows the 'Last-In, Fir...",Queue,Array,Stack,Linked List,C
20,Which city is known as the 'Big Apple'?,Los Angeles,Chicago,Miami,New York City,D

In [27]:
randomnumberList = []
for i in range(10):
    while True:
        random10Numbers = r.randint(0,20)
        if random10Numbers not in randomnumberList:
            randomnumberList.append(random10Numbers)
            break
        else:
            continue
# for questionnumbers in randomnumberList:
#     print(questionare.loc[questionnumbers])


userdataDictionary = {"Names":["Ahmad","Ali","Pyth"],"Score":[9,10,5]}

userDataFrame = pd.DataFrame(userdataDictionary)

In [28]:
userDataFrame.to_csv("StudentScore.csv",index=False)

In [29]:
questionList = [] #Question
for eachRandomNumber in randomnumberList:
    # print(eachRandomNumber)
    singleQuestion = {"Question":questionare.loc[eachRandomNumber,"Question"],"OA":questionare.loc[eachRandomNumber,"Option A"],"OB":questionare.loc[eachRandomNumber,"Option B"],"OC":questionare.loc[eachRandomNumber,"Option C"],"OD":questionare.loc[eachRandomNumber,"Option D"],"RA":questionare.loc[eachRandomNumber,"Right Answer"]}
    questionList.append(singleQuestion)

print(questionList)

[{'Question': 'Which year did the Titanic sink?', 'OA': '1905', 'OB': '1912', 'OC': '1918', 'OD': '1924', 'RA': 'B'}, {'Question': 'What is the value of Pi rounded to two decimal places?', 'OA': '3.12', 'OB': '3.14', 'OC': '3.16', 'OD': '3.18', 'RA': 'B'}, {'Question': 'What is the currency of the United Kingdom?', 'OA': 'Euro', 'OB': 'Dollar', 'OC': 'Pound Sterling', 'OD': 'Yen', 'RA': 'C'}, {'Question': "Which data structure follows the 'Last-In, First-Out' (LIFO) principle?", 'OA': 'Queue', 'OB': 'Array', 'OC': 'Stack', 'OD': 'Linked List', 'RA': 'C'}, {'Question': 'What is the capital city of Japan?', 'OA': 'Seoul', 'OB': 'Beijing', 'OC': 'Bangkok', 'OD': 'Tokyo', 'RA': 'D'}, {'Question': 'Which component is responsible for long-term data storage?', 'OA': 'RAM', 'OB': 'CPU', 'OC': 'HDD/SSD', 'OD': 'GPU', 'RA': 'C'}, {'Question': 'Who painted the Mona Lisa?', 'OA': 'Vincent van Gogh', 'OB': 'Pablo Picasso', 'OC': 'Leonardo da Vinci', 'OD': 'Claude Monet', 'RA': 'C'}, {'Question': "What does 'CPU' stand for?", 'OA': 'Central Processing Unit', 'OB': 'Control Programming Unit', 'OC': 'Computer Personal Unit', 'OD': 'Central Print Utility', 'RA': 'A'}, {'Question': 'What is the powerhouse of the cell?', 'OA': 'Nucleus', 'OB': 'Ribosome', 'OC': 'Mitochondria', 'OD': 'Cytoplasm', 'RA': 'C'}, {'Question': 'Which country is the largest by land area?', 'OA': 'USA', 'OB': 'China', 'OC': 'Russia', 'OD': 'Canada', 'RA': 'C'}]

In [36]:
while True:
    choice = input ("Enter 1 to take the quiz or 2 to exit:")

    if choice  ==  1:
        studentName = input("Enter Your Name:")
        studentScoreSheet= pd.read_csv("StudentScore.csv")
        studentScore = 0
        if studentName in list(studentScoreSheet["Names"]):
            print("You have already taken the quiz")
            continue
        else:
            studentList = [studentName]
            print("User Registered Starting the quiz")
            for question in questionList:
                print(question["Question"])
                print(f"A. {question['OA']}")
                print(f"B. {question['OB']}")
                print(f"C. {question['OC']}")
                print(f"D. {question['OD']}")
                userAnswer = input("Enter Your Answer:")
                if userAnswer == question["RA"]:
                    print("Correct Answer")
                    studentScore = studentScore + 1
                else:
                    print("Wrong Answer")
                    print(f"Correct Answer is {question['RA']}")
                    break




    elif choice == 2:
        print("Quiz Ended")
        break

What is the value of Pi rounded to two decimal places?

In [36]:
import pandas as pd

In [37]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [38]:
dfItems[["Description","Secondary Description"]]

,Description,Secondary Description
0,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...
1,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...
2,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha..."
3,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...
4,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou..."
...,...,...
24697,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ..."
24698,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...
24699,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ..."
24700,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...
24701,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...

In [39]:
set(dfItems["Secondary Brand"])

{'4 Long Lashes',
 '7DAYS',
 'AL haramain',
 'Abdul Samad Al Qurashi',
 'Acqua Di Parisis',
 'Acqua Di Parma',
 'Agatho Perfume',
 'Agent Provocateur',
 'Al Tahara Musk',
 'Al Tahara Royal Muck',
 'Alba Botanica',
 'Albane Noble',
 'Alexandre.J',
 'Alfaparf Milano',
 'Almorel',
 'Alterna',
 'Amara Lenses',
 'Ameera London',
 'Amouage',
 'Anastasia Beverly Hills',
 'Andrea',
 'Anesthesia',
 'Anfas',
 'Angel Barlen',
 'Angel En Provence',
 'Angel Schlesser',
 'Annick Goutal',
 'Answr',
 'Antonio Croce Perfumes',
 'Anua',
 'Aquafresh',
 'Aquarelle Paris',
 'Aquarely',
 'Aramis',
 'Arcancil',
 'Ardell',
 'Argan Deluxe',
 'Arm & Hammer',
 'Armaf',
 'ArtNaturals',
 'Artdeco',
 'Ascada Beauty',
 'Aspel',
 'Assaf',
 'Ateej',
 'Atelier Des Ors',
 'Atelier Flou',
 'Atelier Versace',
 'Atyab Al Marshoud',
 'Aussie',
 'Avène',
 'Awshal Perfumes',
 'Axe',
 'Axis-y',
 'Aya',
 'Ayten',
 'Azzaro',
 'B STYLE',
 'BDK Parfums',
 'BFG',
 'BOIS 1920',
 'BaByliss',
 'Baby Foot',
 'Baby Powder',
 'Balance Cosmetics',
 'Balmy Naturel',
 'Bandido',
 'Barulab',
 'Bath & Body Works',
 'Batiste',
 'Baylis & Harding',
 'Bayt Al Saboun',
 'Be Organic',
 'Beauty Creations',
 'Beauty Formulas',
 'Beauty Legend',
 'Beauty of Joseon',
 'Bebe Perfumes',
 'Becca cosmetics',
 'Beesline',
 'Bell',
 'Benefit',
 'Bentley Perfumes',
 'Beox',
 'Bepanthen',
 'Berdoues Parfums',
 'Bere Beauty',
 'Bergamo',
 'Betres On',
 'Beurer',
 'Beyond Paradise',
 'Beyu',
 'Bic',
 'Bigen',
 'Billie Eilish',
 'Bio Beauty Pierres',
 'Bio Friendly',
 'Bio-Oil',
 'BioBalance',
 'BioBeauty',
 'Bioderma',
 'Biokap',
 'Bioliq',
 'Biore',
 'Biotulin',
 'Biovene',
 'Black Professional',
 'Bloom Dead Sea Life',
 'Boadicea the Victorious',
 'Boucheron',
 'Boulevard',
 'Bourjois',
 'Braun',
 'Briogeo',
 'Britney Spears',
 'Brut',
 'Brylcreem',
 'Burberry',
 'Bvlgari',
 'By Vilain',
 'Byphasse',
 'Byredo Parfums',
 'C.B Deodorant',
 'CHARLOTTE TILBURY',
 'Cacharel',
 'Calvin Klein',
 'Cantu',
 'Capitano',
 'Carefree',
 'Carelika',
 'Careline',
 'Carmex',
 'Carolina Herrera',
 'Cartier',
 'Castelbajac',
 'Cat Of London Lenses',
 'Cathy Doll',
 'Catrice',
 'Celia',
 'Celimax',
 'Cellbn',
 'CeraVe',
 'Cetaphil',
 'Chanel',
 'Charmacy Milano',
 'Chloe',
 'Chopard',
 'Christian Breton',
 'Christian Dior',
 'Christian Laurent',
 'Christian Louboutin',
 'Christian Provenzano',
 'Christine',
 'Chroma',
 'Clarins',
 'Clarisonic',
 'Clean & Clear',
 'Cleanic',
 'Clear',
 'Clinique',
 'Clive Christian',
 'Closeup',
 'Coach',
 'Coco Hair',
 'Coco Hair 24K',
 'Colgate',
 'Color Wow',
 'Correction',
 'Cosmaline',
 'Cosrx',
 'Costume National',
 'Cover Fx',
 'Covermark',
 'Creed',
 'Creightons',
 'Crescina',
 'Crest',
 'DAX',
 'DERMAPILL',
 'DKNY',
 'DUO Adhesives',
 'Dabur Amla',
 'Dahab Lamar Lenses',
 'Daisy Makeup',
 'Dali Beauty',
 'Dancoly',
 'David Beckham',
 'Davidoff',
 'Davini',
 'De Leon Perfumes',
 'Deborah Milano',
 'Declare',
 'Degree',
 'Delongpre',
 'Denim',
 'Dermavive',
 'Dermedic',
 'Dermolab',
 'Dermoviva',
 'Dexe',
 'Diadermine',
 'Dicora Urban Fit',
 'Diesel',
 'Difeel',
 'Disney',
 'Dolce & Gabbana',
 'Donna Karan',
 'Dove',
 'Dr. Althea',
 'Dr. Noora',
 "Dr. Scholl's",
 'Dr.Irena',
 'Dr.Jart+',
 'Dr.Jayjun',
 'Dsquared2',
 'Ducray',
 'Dunhill',
 'Dyson',
 'Déjà Vu Parfums',
 'ENZO',
 'EOS',
 'EVE',
 'Easy Beauty',
 'Ebreez Parfums',
 'Eco MAR',
 'EcoTools',
 'Eden',
 'Egyptian Magic',
 'Electimuss London',
 'Elegance',
 'Elegant Touch',
 'Elgon',
 'Elie Saab',
 'Elizabeth Arden',
 'Elizabeth Taylor',
 'Elizavecca',
 'Emanuel Ungaro',
 'Embryolisse ',
 'Emmanuelle Jane',
 'Enchanteur',
 'Eolux',
 'Eqqual Berry',
 'Ermenegildo Zegna',
 'Escada',
 'Escentric Molecules',
 'Essence',
 'Essential Parfums ',
 'Essie',
 'Estee Lauder',
 'Eternite Beauty perfect',
 'Etude ',
 'Eucerin',
 'Eunyul',
 'Euthymol',
 'Eveline',
 'EyeCandy',
 'Fair & Lovely',
 'Famous Names',
 'Farcom Professional',
 'Fem',
 'Femfresh',
 'Fendi',
 'Fenty Beauty',
 'Ferrari',
 'Fino',
 'Flex Eyes',
 'Florinda',
 'Flormar',
 "Flose'",
 'Floxia',
 'Fogg',
 'Foltene\xa0',
 'Food A Holic',
 'Footlogix',
 'Footner',
 'Foreo',
 'Forever52',
 'Fragrance Du Bois',
 'Franck Olivier',
 'Frederick Malle',
 'Freecia',
 'Freeman',
 'Fresh Look',
 'Fusswohl',
 'GISOU',
 'Gammapiu',
 'Garnier',
 'Gemology',
 'Geparlys Parfums',
 'Gerini',
 'Ghala Zayed',
 'Ghawali',
 'Gillette',
 'Gingie',
 'Giorgio Armani',
 'Gissah',
 'Givenchy',
 'Glam Glow',
 'Glazette',
 'Glossy Blossom',
 'Glow & go',
 'Glow Recipe',
 'Glycerin',
 'Glysolid',
 'Golden Rose',
 'Gosh',
 'Gothic Collection Perfumes',
 'Gucci',
 'Guerlain',
 'Guess',
 'Guy Laroche',
 'H2O1',
 'HFC',
 'Hada Labo',
 'Hadeel Alazawey',
 'Hairburst',
 'Hairotic',
 'Hayari Parfums',
 'Head & Shoulders',
 'Helios Nail',
 'Herbal Essences',
 'Herbamedicus',
 'Hermès',
 'Hi-Speedy',
 'Himalaya',
 'Huda Beauty',
 'Hugo Boss',
 'Hummer',
 'Ibraheem Al Qurashi',
 'Ikoo Infusions',
 'In Sight',
 'Inecto',
 'Inglot',
 'Initio Parfums Prives',
 'Institut Esthederm',
 'Intesa',
 'Irish Spring',
 'IsaDora',
 'Isis Pharma',
 'Issey Miyake',
 'It cosmetics',
 'Itali wax',
 'Itely Hair Fashion',
 'JB Fragrances',
 'Jacomo',
 'Jaguar',
 'Jason Wu',
 'Jean Paul Gaultier',
 'Jennifer Lopez',
 'Jergens',
 'Jeroboam',
 'Jewel',
 'Jimmy Choo',
 'Jkosmec',
 'Jo Malone London',
 'Johan.b Paris',
 'John Varvatos',
 "Johnson's",
 'Joop!',
 'Juicy Couture',
 'Junmei',
 'Just For Men',
 'Juvena',
 'K18',
 'KLAPP',
 'KUNDAL',
 'Kaaral',
 'Kajal',
 'Karen Low',
 'Kat Von D',
 'Kayali',
 'Keiko Mecheri',
 'Kemi Blending Magic',
 'Kenneth Cole',
 'Kenzo',
 'Kerastase',
 'Kevin Murphy',
 'Khatoon Beauty',
 "Kiehl's",
 'Kiko Milano',
 'Kilian',
 'Kim Kardashian',
 'Korloff Paris',
 'Korres',
 'Kylie Cosmetics',
 "L'Arc",
 "L'Artisan Parfumeur",
 "L'Orientale Fragrances",
 "L'Oréal Paris",
 "L'arvore",
 "LA'Fresh",
 'La Cresta',
 'La Roche-Posay',
 'Labello',
 'Laboratorio Olfattivo',
 'Lacoste',
 'Lador',
 'Lady Gaga',
 'Lady Speed Stick',
 'Lalique',
 'Lancaster\xa0',
 'Lancôme',
 'Laneige',
 'Lanvin',
 'Lapitak',
 'Lattafa',
 'Laura Biagiotti',
 'Laura Mercier',
 'Laurent Mazzone Parfums',
 'Laverne',
 'Le Couvent Maison de Parfum',
 'Le Falcone',
 'Lierac Paris',
 'Lionesse',
 'Lirene',
 'Listerine',
 'Locatello',
 'Loewe',
 'Lolita Bonita',
 'Lootah Perfumes',
 'Loreal Paris Professional',
 'Lost',
 'Louis Varel',
 'Louis Vuitton',
 'Lucas',
 'Luseta',
 'M.A.C',
 'M.Asam',
 'M.Micallef',
 'Magnolia',
 'Mahzen',
 'Maison Asrar',
 'Maison Crivelli',
 'Maison De Parfum',
 'Maison Francis Kurkdjian',
 'Maison Noir',
 'Maison Seed',
 'Maison Tahité',
 'Majestic',
 'Majouri',
 'Make Up For Ever',
 'Make up Factory',
 'Malizia',
 'Mancera',
 'Marc Anthony',
 'Marc Jacobs',
 'Marc Joseph',
 'Marc-Antoine Barrois Paris',
 'Marina Lashes',
 'Mario Badescu',
 'Marlies Möller',
 'Marvis',
 'Matiere Premiere',
 'Matin Martin',
 'Matrix',
 'Maui',
 'Mauresque',
 'Mavala',
 'Max Factor',
 'Max Life',
 'Maxi',
 'Maybelline',
 'Medicube',
 'Memo Paris',
 'Mercedes-Benz',
 'Merimieu',
 'Mesauda',
 'Mesauda Milano',
 'Mesauda Professional',
 'Michael Buble',
 'Michael Kors',
 'Mielle',
 'Milani',
 'Mimesis Parfums',
 'Mimosa Makeup',
 'Mina Alsheikhly',
 'Mio Skin',
 'Missha',
 'Missoni',
 'Mitchum ',
 'Miu Miu',
 'Mixsoon',
 'Mixueer',
 'Mon Reve',
 'Mont Blanc',
 'Montale Perfumes',
 'Montana Parfum',
 'Moremo',
 'Moresque',
 'Moriscent',
 'Morphe',
 'Moser',
 'Mumuso',
 'My Little Miracle',
 'Myrurgia 1916',
 'NYC',
 'NYX Professional Makeup',
 'Nabla',
 'Narciso Rodriguez',
 'Nars',
 'Nasamat',
 'Nashi',
 'Nasomatto',
 'Natural Looks',
 'Nature Republic',
 'Nawras Sattar',
 "Ne'emah",
 'Neutrogena',
 'Nimnima',
 'Nina Ricci',
 'Nishane',
 'Nitro',
 'Nivea',
 'Nobel',
 'Nobel Royale',
 'Noosoo',
 'Nora Bo Awadh',
 'Note',
 'Now',
 'OFRA Cosmetics',
 'OGX',
 'OZ Naturals',
 'Olaplex',
 'Olay',
 'Old Spice',
 'Olivia Garden',
 'On Line',
 'Oral-B',
 'Orens Parfums',
 'Orga',
 'Origins',
 'Orland Pita Play',
 'Oros',
 'Ossum',
 'Others',
 'Ouai',
 'Oud Story',
 'Pacinos',
 'Paco Rabanne',
 'Palladio',
 "Palmer's",
 'PanOxyl',
 'Panouge',
 'Pantene',
 'Parachute',
 'Parfums De Marly',
 "Parfums d'Elmar",
 'Paris Bleu',
 'Paris Hilton',
 'Paul Emilien',
 'Paul Smith',
 'Payot',
 "Penhaligon's London",
 'Perfect',
 'Perfume De Major',
 'Pernoire',
 'Perris Monte Carlo ',
 'Perry Ellis',
 'Petite Maison',
 'Pfb Vanish',
 'Ph Argan & Keratin',
 'Pharmaceris',
 'Philipp Plein ',
 'Philips',
 'Philly & Phill',
 'Phyto',
 'Pigaviva',
 'Pinky Goat',
 'Pixi Beauty',
 'Pk Pura',
 'Polso',
 'Ponds',
 'Prada',
 'Primaderm',
 'Prive Deo Spray',
 'Provoc',
 'Puccini',
 'Pupa Milano',
 'Pura Kosmetica',
 'Pure Essence Fragrance',
 'Puring',
 'Quattrolio',
 'R+Co',
 'Radha Beauty',
 'Ralph Lauren',
 'Ramla',
 'Ramon Bejar',
 'Ramon Monegal',
 'Rare Beauty ',
 'Rasasi',
 'Real Techniques',
 'Reebok',
 'Remia',
 'Remington',
 'Retrouvailles Paris',
 'Revivre',
 'Revlon',
 'Revolution',
 'Revuele',
 'Rexona',
 'Rhode ',
 'Richenna',
 'Right Guard',
 'Rimmel London',
 'Rituals',
 'Roberto Cavalli',
 'Rochas',
 'Roja ',
 'Romeo Gigli',
 'Rose Baie Paris',
 'Rosella',
 'Rosendo Mateu',
 'Royal De Maison',
 'Royal Platinume',
 'Rude Makeup',
 'SH!FTi',
 'SKIN1004',
 'SLA Paris',
 'SVR',
 'Sabalon',
 'Sally Hansen',
 'Salvador Dali',
 'Salvatore Ferragamo',
 'Sancy Paris',
 'Sanex',
 'Santoro London',
 'Sara Khatoon',
 'Savoo',
 'Schwarzkopf',
 'Sebamed',
 'Seboradin',
 'Secret',
 'Sence Beauty',
 'Sensodyne',
 'Sephora',
 'Sergio Vallanti',
 'Seventeen',
 'Shangpree',
 'Shay & Blue',
 'Shea Moisture',
 'Sheglam',
 'Shiseido',
 'Sigma Beauty',
 'Signal',
 'Signature',
 'Silvercrest',
 'Simple',
 'Sisley Paris',
 'Sistelle Paris',
 'Skala',
 'Skin Proud',
 'Skincode',
 'Skinlab',
 'Slazenger',
 'Smashbox',
 'Soft Foot',
 'Soft Skin',
 'Sol De Janeiro',
 'Solfege Collection',
 'Some By Mi',
 'Soskin',
 'Sosoim',
 'Sospiro',
 'Speed Stick',
 'Spider Man',
 'Spirit Of Kings',
 'St.Ives',
 'Stamp',
 'Star Wars',
 'Stellary',
 'Steve Martin Paris',
 'Sturgeon',
 'Suave',
 'Subrina',
 'Sugar Bear Hair',
 'Summer Fridays',
 "Summer's Eve",
 'Sunny Isle',
 'Swiss Image',
 'Syoss',
 'TOCOBO',
 "TRESemme'",
 'TUMI',
 'Tabac Original',
 'Tailaimei',
 'Tarte',
 'Tea Tree',
 'Teba Khalil',
 'Ted Baker',
 'Ted Lapidus Parfume',
 'Teotema',
 'Thayers',
 'The Balm',
 'The Body Shop',
 'The Breath.Co',
 'The Fragrance Kitchen',
 'The House Of Oud',
 'The Inkey List',
 'The Ordinary',
 'The Palace Of Perfumes',
 'The Purest Solutions',
 'The Scent',
 'The Secret Frankincense',
 'The Woods Collection',
 'TheraBreath',
 'Thierry Mugler',
 'Thomas Kosmala',
 'Tiamo',
 'Titania',
 'Tiziana Terenzi',
 'Tizo',
 'Tom Ford',
 'Tonymoly',
 'Too Faced',
 'Top Notch',
 'Tory Burch',
 'Trim',
 'Trussardi',
 'Tsubaki',
 'Turquaz',
 'Twisted Sista',
 'U.B.U',
 'Ulric de Varens',
 'Ultra',
 'Under Twenty',
 "Unique'e Luxury",
 'Urban Decay',
 'V Canto',
 'VIVIAN GRAY',
 'Valentino',
 'Van Cleef & Arpels',
 'Vaseline',
 'Veet',
 'Vegan',
 'Vejetree',
 'Venuse',
 'Versace',
 'Versailles Beauté',
 'Vertus Paris',
 'Vichy',
 "Victoria's Secret",
 'Victorinox ',
 'Viktor & Rolf',
 'Vitadea',
 'Viva',
 'Vogue',
 'Voilier',
 'Voox',
 'Voyage',
 'Western Valley',
 'Wet N Wild',
 'White Glo',
 'Widian Arabia',
 'Wild Science Lab',
 'Wisdom',
 "Women'Secret",
 'Xerjoff',
 'YNM',
 'Yougee',
 'Youmi Beauty',
 'Yucca',
 'Yves De Sistelle',
 'Yves Rocher',
 'Yves Saint Laurent',
 'ZK Beauty',
 'Zeena',
 'bye bye blemish',
 'dr.Clinic',
 'e.l.f.',
 'ego QV',
 'katrina',
 'kirkland signature',
 'lux',
 nan,
 'oman luxury',
 'purederm',
 'sheikha',
 'so...?'}

In [40]:
dfItems[dfItems["Secondary Brand"]=="Nivea"]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
15,NaN,390143,جل استحمام بزيت جوز الهند والجوجوبا 750 مل,Coconut & Jojoba Oil shower gel 750 ml,4005900998811,NaN,"8,000د.ع",جل استحمام بزيت جوز الهند والجوجوبا يمنحكِ بشر...,Shower gel with coconut and jojoba oil gives y...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,"9,000د.ع",بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No
810,https://www.storeakmedia.com/storeak-erp/Store...,359628,جل الاستحمام كريم كير750 مل,Shower Gel Creme Care 750 ml,4006000095752,0,"8,000د.ع",غسول الجسم ينظف بشرتكِ بلطف أثناء الاستحمام، ب...,This body wash gently cleanses your skin while...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
814,https://www.storeakmedia.com/storeak-erp/Store...,359607,جل استحمام كريم سموث 750 مل,Shower Gel Cream Smooth 750 ml,4006000095738,0,"8,000د.ع",جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
815,https://www.storeakmedia.com/storeak-erp/Store...,359606,جل استحمام كريم سوفت 750 مل,Shower Gel Creme Soft 750 ml,4006000095776,0,"8,000د.ع",جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22999,https://www.storeakmedia.com/storeak-erp/Store...,316752,رغوة حلاقة منعشة للبشرة الحساسة 200 مل,Sensitive Cooling Shaving Foam 200 ml,4005900378255,0,"6,000د.ع","رغوة الحلاقة للرجال, تعمل على تنعيم اللحية لحل...",Men's Shaving Foam Softens the beard for a clo...,|نيفيا|Nivea|العناية بالرجال جل ورغوة الحلاقة|...,NaN,العناية بالرجال‎ -> اللحية‎ -> جل & رغوة الحلاقة,نيفيا,Nivea,No
23063,https://www.storeakmedia.com/storeak-erp/Store...,316688,غسول التنظيف العميق للوجه واللحية 100 مل,Deep Face & Beard Wash Cleanser 100 ml,4005900517951,0,"7,750د.ع","غسول الوجه للرجال, تركيبة مبتكرة بالفحم الأسود...","Face wash for men, an innovative formula with ...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23064,https://www.storeakmedia.com/storeak-erp/Store...,316687,غسول منعش للوجه 100 مل,Refreshing Face Wash 100 ml,4005808228010,0,"7,250د.ع","غسول الوجه للرجال, يزيل الأوساخ والزيوت الزائد...","Face wash for men, removes dirt and excess oil...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23065,https://www.storeakmedia.com/storeak-erp/Store...,316686,مقشر الوجه ديب بقوة الكاربون 75 مل,Deep Black Carbon Face Scrub 75 ml,4005900678522,0,"7,750د.ع","مقشر الوجه للرجال, بتركيبة الفحم الأسود التي ت...","Facial scrub for men, with a black carbon form...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23066,https://www.storeakmedia.com/storeak-erp/Store...,316685,غسول الوجه ديب لازالة الحبوب وزيوت البشرة 100 مل,Deep Pimple & Oil Clear Face Wash 100 ml,4005900818119,0,"8,500د.ع","غسول الوجه للرجال, يقوم بتنظيف وتنقية البشرة ب...","Facial wash for men, it gently cleanses and pu...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No

In [86]:
MessyPrice =  list(dfItems["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))
dfItems["Price"]=CleanedPrice

In [42]:
CleanedPrice

[25000,
 300000,
 30000,
 0,
 15000,
 15000,
 18000,
 15000,
 7750,
 15500,
 65000,
 3500,
 19000,
 38000,
 15500,
 8000,
 115500,
 6500,
 30000,
 20000,
 4000,
 30000,
 4000,
 32000,
 4000,
 30000,
 45000,
 37000,
 30000,
 10000,
 3500,
 3500,
 45000,
 45000,
 15000,
 50000,
 7500,
 120000,
 15000,
 5000,
 120000,
 5000,
 4500,
 5000,
 75000,
 13000,
 75000,
 6500,
 19000,
 6500,
 6500,
 6500,
 28000,
 5000,
 5000,
 8500,
 5000,
 5000,
 17000,
 15000,
 19750,
 19750,
 27000,
 27000,
 30000,
 30500,
 23000,
 9000,
 25000,
 9000,
 25000,
 32000,
 16000,
 9000,
 27000,
 9000,
 27000,
 370000,
 10500,
 10500,
 37500,
 60000,
 7000,
 120000,
 18500,
 25000,
 39000,
 22000,
 19000,
 163250,
 255250,
 72000,
 45000,
 124250,
 28750,
 109250,
 26250,
 26250,
 71000,
 92500,
 18250,
 92500,
 50000,
 25000,
 66000,
 25000,
 25000,
 35000,
 25000,
 23750,
 25000,
 28000,
 19000,
 15000,
 15000,
 25000,
 8000,
 15000,
 15000,
 7000,
 30000,
 18000,
 7000,
 7000,
 7000,
 7000,
 17000,
 17000,
 17000,
 17000,
 8000,
 15000,
 8000,
 15000,
 15000,
 15000,
 12000,
 12000,
 15000,
 17000,
 17000,
 17000,
 15000,
 15000,
 17000,
 8000,
 31000,
 15000,
 34000,
 15000,
 34000,
 40000,
 17000,
 55500,
 17000,
 60000,
 270250,
 270250,
 150000,
 150000,
 70000,
 60000,
 60000,
 105000,
 44000,
 12000,
 8500,
 16000,
 8500,
 413250,
 8500,
 25000,
 15000,
 35000,
 35000,
 10000,
 3500,
 12000,
 25000,
 30000,
 68000,
 365500,
 129000,
 123250,
 158000,
 129000,
 123250,
 129000,
 123250,
 346750,
 53500,
 94250,
 43500,
 82000,
 82000,
 46500,
 9000,
 9000,
 4000,
 0,
 6500,
 6500,
 6500,
 6500,
 6500,
 78000,
 25000,
 9500,
 3000,
 3000,
 3000,
 24000,
 15000,
 15000,
 14000,
 10000,
 9000,
 10000,
 15000,
 15000,
 14000,
 25000,
 15000,
 19500,
 34750,
 34750,
 34750,
 19000,
 57000,
 55000,
 1,
 25000,
 50000,
 20000,
 16000,
 435000,
 28000,
 32000,
 25000,
 28000,
 6000,
 18000,
 18000,
 16000,
 17500,
 12000,
 18000,
 95000,
 18000,
 20000,
 18000,
 18000,
 20000,
 3500,
 4000,
 14000,
 27500,
 25000,
 22000,
 20000,
 22000,
 22000,
 22000,
 22000,
 158000,
 152750,
 159500,
 159500,
 145000,
 153000,
 13750,
 530000,
 17500,
 24000,
 26000,
 40000,
 75500,
 70000,
 116250,
 89000,
 59000,
 28000,
 28000,
 14750,
 23750,
 31250,
 14500,
 11250,
 15750,
 295000,
 17000,
 295000,
 28250,
 295000,
 16750,
 17250,
 19750,
 295000,
 295000,
 19250,
 295000,
 16000,
 295000,
 25500,
 295000,
 14250,
 31250,
 295000,
 24250,
 295000,
 38750,
 13250,
 25000,
 21500,
 295000,
 25000,
 25000,
 18750,
 295000,
 17500,
 295000,
 14500,
 295000,
 20750,
 19000,
 295000,
 20000,
 25250,
 295000,
 30750,
 9750,
 24000,
 9000,
 24000,
 55000,
 27750,
 8000,
 5750,
 26000,
 7250,
 4000,
 22000,
 5000,
 5250,
 7250,
 6500,
 5250,
 3250,
 7250,
 139500,
 6500,
 6500,
 6500,
 85750,
 98250,
 338250,
 775000,
 59000,
 15000,
 12000,
 12000,
 12000,
 90000,
 50000,
 22000,
 24000,
 169000,
 22000,
 22000,
 50000,
 68000,
 68000,
 39000,
 100750,
 68000,
 59000,
 68000,
 68000,
 68000,
 3500,
 45000,
 45000,
 75000,
 8500,
 33000,
 5000,
 100750,
 4000,
 9500,
 14000,
 23250,
 31000,
 15000,
 15000,
 70000,
 110000,
 76750,
 7000,
 7000,
 23250,
 129000,
 24000,
 71500,
 23000,
 56000,
 7000,
 23000,
 15000,
 7000,
 7000,
 5000,
 15000,
 15000,
 15000,
 20000,
 20000,
 12000,
 7000,
 15000,
 3000,
 5000,
 8000,
 14000,
 231500,
 18750,
 14000,
 5000,
 5000,
 975000,
 367000,
 975000,
 681000,
 681000,
 900000,
 825000,
 5000,
 5000,
 6000,
 5000,
 5000,
 5000,
 6000,
 6000,
 14000,
 14000,
 14000,
 14000,
 6000,
 6000,
 4500,
 4500,
 14000,
 29000,
 15000,
 4500,
 14000,
 25000,
 14000,
 22000,
 24000,
 15000,
 14000,
 70000,
 15000,
 60000,
 14000,
 18000,
 274000,
 18000,
 79000,
 18000,
 18000,
 18000,
 10000,
 18000,
 136500,
 18000,
 18000,
 136500,
 178250,
 130000,
 114000,
 173500,
 36500,
 127000,
 170500,
 121000,
 131750,
 1500,
 100750,
 170000,
 50000,
 50000,
 58000,
 40000,
 40000,
 95000,
 75000,
 40000,
 40000,
 40000,
 40000,
 40000,
 65000,
 40000,
 37000,
 37000,
 37000,
 37000,
 37000,
 116250,
 37000,
 37000,
 37000,
 35000,
 75000,
 82000,
 114000,
 84000,
 48000,
 128000,
 95000,
 89000,
 51000,
 64000,
 51000,
 31000,
 40000,
 9000,
 40000,
 40000,
 40000,
 7500,
 40000,
 75000,
 75000,
 75000,
 50000,
 43500,
 236500,
 43500,
 50000,
 50000,
 13250,
 2000,
 3000,
 3500,
 2500,
 75000,
 26000,
 2000,
 2000,
 25000,
 75000,
 34500,
 75000,
 19000,
 96000,
 9000,
 127000,
 127000,
 85250,
 6000,
 108500,
 6000,
 6000,
 6000,
 6000,
 90000,
 62000,
 33500,
 59000,
 162750,
 124000,
 5000,
 5000,
 99750,
 83000,
 65000,
 107000,
 147000,
 50000,
 128000,
 39000,
 42000,
 53000,
 48000,
 108000,
 46000,
 49000,
 57000,
 42000,
 229000,
 208000,
 203000,
 85000,
 118000,
 193000,
 74000,
 65000,
 110000,
 113000,
 63000,
 8000,
 7000,
 15000,
 15000,
 12000,
 15000,
 6000,
 6000,
 8000,
 8000,
 6000,
 7000,
 8000,
 163000,
 137500,
 143500,
 165500,
 231750,
 204000,
 100000,
 26750,
 10000,
 15000,
 40000,
 22000,
 28000,
 28000,
 93000,
 131250,
 115500,
 92750,
 0,
 0,
 7500,
 100000,
 90000,
 120000,
 7500,
 87000,
 65000,
 65000,
 4500,
 40000,
 40000,
 60000,
 60000,
 70000,
 65000,
 120000,
 120000,
 346000,
 65000,
 65000,
 38000,
 40000,
 131250,
 106500,
 100500,
 100750,
 105500,
 150000,
 150000,
 130500,
 115500,
 192000,
 192000,
 192000,
 421750,
 123000,
 76750,
 396000,
 135000,
 396000,
 85000,
 195000,
 85000,
 5000,
 85750,
 75500,
 100000,
 15000,
 52750,
 121000,
 131750,
 69500,
 74500,
 162750,
 108500,
 48500,
 46500,
 248000,
 170500,
 170500,
 101250,
 6500,
 42000,
 80000,
 80000,
 35000,
 65000,
 42250,
 74000,
 123250,
 66750,
 100750,
 66750,
 71750,
 71750,
 59000,
 66750,
 63500,
 66750,
 542500,
 434000,
 434000,
 91500,
 151750,
 100750,
 265000,
 265000,
 465000,
 364250,
 4000,
 64500,
 4000,
 3500,
 13000,
 45000,
 18500,
 25750,
 25000,
 25000,
 68000,
 25000,
 25000,
 13250,
 30000,
 25000,
 5000,
 25000,
 15000,
 25000,
 0,
 2500,
 10000,
 3500,
 0,
 3500,
 80500,
 100750,
 116250,
 207750,
 108000,
 105500,
 3500,
 116250,
 100750,
 147250,
 0,
 5000,
 5000,
 7000,
 7000,
 8000,
 7000,
 5000,
 3500,
 139500,
 7500,
 7500,
 5000,
 6000,
 3500,
 62000,
 29500,
 20250,
 65000,
 162500,
 142250,
 80500,
 15000,
 15000,
 15000,
 15000,
 15000,
 15000,
 15000,
 15000,
 30000,
 158250,
 126750,
 15000,
 10000,
 10000,
 15000,
 10000,
 15000,
 6000,
 13000,
 25000,
 4500,
 30000,
 12000,
 14000,
 42000,
 29000,
 9000,
 8000,
 4000,
 8500,
 10000,
 8000,
 8000,
 8000,
 5000,
 6000,
 6000,
 6000,
 116250,
 85250,
 98250,
 69750,
 39250,
 131750,
 37750,
 74500,
 72750,
 131750,
 117750,
 59000,
 120000,
 69750,
 139500,
 8000,
 71250,
 35000,
 25000,
 25000,
 26000,
 26000,
 25000,
 25000,
 30000,
 30000,
 24000,
 30000,
 30000,
 30000,
 30000,
 140000,
 116250,
 121000,
 54250,
 121750,
 90000,
 129000,
 108500,
 114750,
 74500,
 77500,
 62000,
 200000,
 59750,
 141250,
 139500,
 74500,
 127750,
 30000,
 30000,
 35000,
 100000,
 14750,
 16000,
 16000,
 12500,
 12500,
 12500,
 12500,
 67000,
 45000,
 36000,
 32000,
 30000,
 24000,
 19000,
 24000,
 29000,
 29000,
 24000,
 26000,
 26000,
 26000,
 70000,
 32000,
 32000,
 32000,
 32000,
 26000,
 32000,
 99250,
 24000,
 16000,
 24000,
 24000,
 16000,
 19000,
 16000,
 24000,
 19000,
 14000,
 19000,
 321750,
 14000,
 14000,
 29000,
 36000,
 14000,
 19000,
 19000,
 32000,
 19000,
 32000,
 32000,
 15000,
 36000,
 36000,
 67000,
 54000,
 24000,
 38000,
 15000,
 28000,
 28000,
 48000,
 27000,
 24000,
 27000,
 30000,
 30000,
 30000,
 36000,
 52000,
 225000,
 16750,
 16000,
 16000,
 43250,
 42500,
 99250,
 42500,
 42500,
 42500,
 49500,
 49500,
 49500,
 49500,
 21750,
 29500,
 21750,
 25000,
 25000,
 35000,
 32000,
 25000,
 28000,
 32000,
 30000,
 30000,
 64000,
 104000,
 64000,
 168000,
 225000,
 6500,
 6500,
 6500,
 395250,
 25000,
 25000,
 25000,
 100750,
 25000,
 25000,
 25000,
 95000,
 145000,
 94250,
 23000,
 26000,
 23000,
 23000,
 30000,
 27000,
 30000,
 25000,
 23000,
 35000,
 ...]

In [43]:
dfItems["Price"]=CleanedPrice

In [44]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [45]:
dfItems[(dfItems["Secondary Brand"]=="Nivea") & (dfItems["Price"]>1000)]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
15,NaN,390143,جل استحمام بزيت جوز الهند والجوجوبا 750 مل,Coconut & Jojoba Oil shower gel 750 ml,4005900998811,NaN,8000,جل استحمام بزيت جوز الهند والجوجوبا يمنحكِ بشر...,Shower gel with coconut and jojoba oil gives y...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,9000,بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No
810,https://www.storeakmedia.com/storeak-erp/Store...,359628,جل الاستحمام كريم كير750 مل,Shower Gel Creme Care 750 ml,4006000095752,0,8000,غسول الجسم ينظف بشرتكِ بلطف أثناء الاستحمام، ب...,This body wash gently cleanses your skin while...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
814,https://www.storeakmedia.com/storeak-erp/Store...,359607,جل استحمام كريم سموث 750 مل,Shower Gel Cream Smooth 750 ml,4006000095738,0,8000,جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
815,https://www.storeakmedia.com/storeak-erp/Store...,359606,جل استحمام كريم سوفت 750 مل,Shower Gel Creme Soft 750 ml,4006000095776,0,8000,جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22999,https://www.storeakmedia.com/storeak-erp/Store...,316752,رغوة حلاقة منعشة للبشرة الحساسة 200 مل,Sensitive Cooling Shaving Foam 200 ml,4005900378255,0,6000,"رغوة الحلاقة للرجال, تعمل على تنعيم اللحية لحل...",Men's Shaving Foam Softens the beard for a clo...,|نيفيا|Nivea|العناية بالرجال جل ورغوة الحلاقة|...,NaN,العناية بالرجال‎ -> اللحية‎ -> جل & رغوة الحلاقة,نيفيا,Nivea,No
23063,https://www.storeakmedia.com/storeak-erp/Store...,316688,غسول التنظيف العميق للوجه واللحية 100 مل,Deep Face & Beard Wash Cleanser 100 ml,4005900517951,0,7750,"غسول الوجه للرجال, تركيبة مبتكرة بالفحم الأسود...","Face wash for men, an innovative formula with ...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23064,https://www.storeakmedia.com/storeak-erp/Store...,316687,غسول منعش للوجه 100 مل,Refreshing Face Wash 100 ml,4005808228010,0,7250,"غسول الوجه للرجال, يزيل الأوساخ والزيوت الزائد...","Face wash for men, removes dirt and excess oil...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23065,https://www.storeakmedia.com/storeak-erp/Store...,316686,مقشر الوجه ديب بقوة الكاربون 75 مل,Deep Black Carbon Face Scrub 75 ml,4005900678522,0,7750,"مقشر الوجه للرجال, بتركيبة الفحم الأسود التي ت...","Facial scrub for men, with a black carbon form...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23066,https://www.storeakmedia.com/storeak-erp/Store...,316685,غسول الوجه ديب لازالة الحبوب وزيوت البشرة 100 مل,Deep Pimple & Oil Clear Face Wash 100 ml,4005900818119,0,8500,"غسول الوجه للرجال, يقوم بتنظيف وتنقية البشرة ب...","Facial wash for men, it gently cleanses and pu...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No

In [46]:
dfItems.loc[dfItems["Id"]==359629,"Price"]=15000

In [47]:
dfItems[dfItems["Id"]==359629]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,15000,بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No

In [48]:
dfItems[["Secondary Name", "Price"]]

                                          Secondary Name   Price
0                             Pleasure Lip Oil 001, 5 ml   25000
1                       Bleu De Chanel L'Exclusif Parfum  300000
2                        Seapuri Scalpy Hair Serum 20 ml   30000
3                                     Ganymede EDP 50 ml       0
4                  Brow Styling Gel With Peptides 15 ml    15000
...                                                  ...     ...
24697              Lime & Matcha Hair & Body Mist 150 ml   16500
24698       Pink Pepper & Lychee Hair & Body Mist 150 ml   12000
24699  Glam & Doll Boost Lash Growth Volume Mascara 8 ml   10500
24700                      Body Mist Passion Fruit150 ml   15000
24701              Volume Supreme Mascara (1Black) 15 ml   22500

[24702 rows x 2 columns]

In [49]:
dfItems["New Secondary Name"] = dfItems["Secondary Name"].str.cat(dfItems['Price'].astype(str),sep="")

In [50]:
dfItems[["Secondary Name","New Secondary Name"]]

,Secondary Name,New Secondary Name
0,"Pleasure Lip Oil 001, 5 ml","Pleasure Lip Oil 001, 5 ml25000"
1,Bleu De Chanel L'Exclusif Parfum,Bleu De Chanel L'Exclusif Parfum300000
2,Seapuri Scalpy Hair Serum 20 ml,Seapuri Scalpy Hair Serum 20 ml30000
3,Ganymede EDP 50 ml,Ganymede EDP 50 ml0
4,Brow Styling Gel With Peptides 15 ml,Brow Styling Gel With Peptides 15 ml 15000
...,...,...
24697,Lime & Matcha Hair & Body Mist 150 ml,Lime & Matcha Hair & Body Mist 150 ml16500
24698,Pink Pepper & Lychee Hair & Body Mist 150 ml,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,Body Mist Passion Fruit150 ml,Body Mist Passion Fruit150 ml15000
24701,Volume Supreme Mascara (1Black) 15 ml,Volume Supreme Mascara (1Black) 15 ml22500

In [51]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [52]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [44]:
dfItems.drop(columns=["Sub Description","Secondary Sub Description"],inplace=True)

In [45]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [46]:
dfItems.rename(columns={"English Name":"English Names","Name":"Arabic Names"},inplace=True)

In [47]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [48]:
dfCollections
# Drop columns size, Unit level
# Clean Price column
# Concatenate Item name with color & Secondary Item Name with Secondary Color
# Assign to the same columns

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [49]:
dfCollections.drop(columns=["Size","Unit Level"],inplace=True)

In [50]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [51]:
MessyPrice =  list(dfCollections["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))
dfCollections["Price"]=CleanedPrice

In [52]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,420000,3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,300000,3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,19750,7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,19750,7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,19750,7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,17250,3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,17000,697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,6500,697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,17000,697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,6500,697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [53]:
dfCollections["Item Name"] = dfCollections["Item Name"].str.cat(dfCollections['Color'].astype(str),sep="")

In [54]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum,NaN,420000,3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum,NaN,300000,3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick,#F3D5C6,19750,7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick,#F2B2B9,19750,7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick,#AF8E7A,19750,7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,17250,3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint,NaN,17000,697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint,NaN,6500,697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint,NaN,17000,697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint,NaN,6500,697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [55]:
dfCollections["Secondary Item Name"] = dfCollections["Secondary Item Name"].str.cat(dfCollections['Secondary Color'].astype(str),sep="")

In [56]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [57]:
dfCollections.drop(columns=["Color","Secondary Color"],inplace=True)

In [58]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,True,https://www.storeakmedia.com/storeak-erp/Store...

In [59]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [60]:
# Drop Sub Description and Secondary Sub description
# price Clean
# Filter that how many items has Collections as true

In [61]:
dfItems.drop(columns=["Sub Description","Secondary Sub Description"],inplace=True)

KeyError: "['Sub Description', 'Secondary Sub Description'] not found in axis"

In [62]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [63]:
MessyPrice =  list(dfItems["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))
dfItems["Price"]=CleanedPrice

In [64]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [65]:
dfItems[dfItems["Has Collections"]=="Yes"]

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
60,https://www.storeakmedia.com/storeak-erp/Store...,364804,هايلايتر ستك,The Glow Stick,NaN,NaN,19750,هايلايتر بتركيبة كريمية خفيفة الوزن تنير البشر...,"A lightweight, creamy highlighter that instant...",المكياج‎ -> الخدود‎ -> اضاءة‎ -> ستك,إيزادورا,IsaDora,Yes
61,https://www.storeakmedia.com/storeak-erp/Store...,364793,كونتور ستك,The Contour Stick,NaN,NaN,19750,كونتور يتميز بتركيبة كريمية ناعمة سهلة الدمج م...,"Contour features a soft, creamy formula that b...",المكياج‎ -> الوجه‎ -> كونتور,إيزادورا,IsaDora,Yes
94,https://www.storeakmedia.com/storeak-erp/Store...,364529,كريم أساس سائل ميكس جلو تينت إسنس,Liquid Foundation Healthy Mix Glow Tint Essence,NaN,NaN,28750,كريم اساس يتميز بتركيبة مبتكرة تجمع بين العناي...,A foundation with an innovative formula that c...,المكياج‎ -> الوجه‎ -> كريم أساس‎ -> جميع انواع...,برجواز,Bourjois,Yes
107,https://www.storeakmedia.com/storeak-erp/Store...,364479,كريم أساس فوندوتينتا وندر مي ديفندر بعامل حماي...,Fondotinta Wonder Me Defender SPF 50,NaN,NaN,35000,كريم أساس مقاوم للماء والرطوبة، يوفر تغطية قاب...,"A water resistant, humidity resistant foundati...",المكياج‎ -> الوجه‎ -> كريم أساس‎ -> جميع انواع...,بوبا ميلانو,Pupa Milano,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8252,https://www.storeakmedia.com/storeak-erp/Store...,332030,كونسيلر دريم لومي تاتش,Dream Lumi Touch Concealer,NaN,NaN,6250,كونسيلر سائل يمتاز بتركيبة ناعمة تضيء وتغطي ال...,A liquid concealer with a smooth texture that ...,"المكياج‎ -> الوجه‎ -> كونسيلر & مصحح,المكياج‎ ...",ميبيلين,Maybelline,Yes
8253,https://www.storeakmedia.com/storeak-erp/Store...,332028,كريم أساس سائل دريم ساتين 30 مل,Dream Satin Liquid Foundation 30 ml,NaN,NaN,21750,كريم اساس يتميز بتركيبة سائلة مع خصائص ترطيب ل...,Foundation that is characterized by a liquid f...,المكياج‎ -> الوجه‎ -> كريم أساس‎ -> جميع انواع...,ميبيلين,Maybelline,Yes
8254,https://www.storeakmedia.com/storeak-erp/Store...,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,NaN,NaN,17250,كونسيلر مصحح بخصائص مضادة للشيخوخة تخفي علامات...,A corrective concealer with anti aging propert...,"المكياج‎ -> الوجه‎ -> كونسيلر & مصحح,المكياج‎ ...",ميبيلين,Maybelline,Yes
23139,https://www.storeakmedia.com/storeak-erp/Store...,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,C - 3,6500,غسول الفم والاسنان لتقليل نزيف والتهابات اللثة...,Mouthwash and teeth to reduce bleeding and inf...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ثيرابريث,TheraBreath,Yes
23141,https://www.storeakmedia.com/storeak-erp/Store...,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,D - 4,6500,غسول الفم والاسنان يعمل على تحييد البكتيريا ال...,Mouthwash neutralizes sulfur producing bacteri...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ذا بريث كو,The Breath.Co,Yes

In [66]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,True,https://www.storeakmedia.com/storeak-erp/Store...

In [67]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [68]:
# check by comparing id from boths sheets and see if all the products from
#Collections sheet exist in items sheet

In [69]:
# Merge both sheets
# Compare both ids = On id's getting matched retrieve the information
# For the specific product Id, Name , Secondary Name , barcode , price from collection
# for same product you can get description , secondary Description, Menu , Brand and Secondary brand from items sheet
# Attach new row at the end of items sheet

In [70]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [71]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,True,https://www.storeakmedia.com/storeak-erp/Store...

In [72]:
CollectoinSheetIds = dfCollections["Item Id"]

In [73]:
CollectoinSheetIds

0        390187
1        390187
2        364804
3        364804
4        364793
          ...
14481    332027
14482    316612
14483    316612
14484    316610
14485    316610
Name: Item Id, Length: 14486, dtype: int64

In [74]:
ItemSheetIds =  dfItems["Id"].tolist()

In [75]:
ItemSheetIds
for eachId in CollectoinSheetIds:
    if eachId in ItemSheetIds:
        picture  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Picture"]
        Barcode  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Barcode"]
        Item_Name  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Item Name"]
        Secondary_Item_Name  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Secondary Item Name"]
        Price  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Price"]

        Description  = dfItems.loc[dfItems["Id"]==eachId,"Description"]
        Secondary_Description  = dfItems.loc[dfItems["Id"]==eachId,"Secondary Description"]
        Menu  = dfItems.loc[dfItems["Id"]==eachId,"Menu"]
        Brand  = dfItems.loc[dfItems["Id"]==eachId,"Brand"]
        Secondary_Brand  = dfItems.loc[dfItems["Id"]==eachId,"Secondary Brand"]
        currentrowNumber = len(dfItems["Id"])
        dfItems.loc[currentrowNumber] = [picture,eachId,Item_Name,Secondary_Item_Name,Barcode,"NAN",Price,Description,Secondary_Description,Menu,Brand,Secondary_Brand,False]
        print("Matched"+" "+str(eachId)+" "+str(currentrowNumber))

    else:
        print("Not Matched")

Matched 390187 24702
Matched 390187 24703
Matched 364804 24704
Matched 364804 24705
Matched 364793 24706
Matched 364793 24707
Matched 364793 24708
Matched 364793 24709
Matched 364529 24710
Matched 364529 24711
Matched 364529 24712
Matched 364479 24713
Matched 364479 24714
Matched 364479 24715
Matched 364030 24716
Matched 364030 24717
Matched 364030 24718
Matched 364030 24719
Matched 363953 24720
Matched 363953 24721
Matched 363951 24722
Matched 363951 24723
Matched 363949 24724
Matched 363949 24725
Matched 363948 24726
Matched 363948 24727
Matched 363946 24728
Matched 363946 24729
Matched 363523 24730
Matched 363523 24731
Matched 363523 24732
Matched 363523 24733
Matched 363147 24734
Matched 363147 24735
Matched 363104 24736
Matched 363104 24737
Matched 362740 24738
Matched 362740 24739
Matched 362705 24740
Matched 362705 24741
Matched 362294 24742
Matched 362294 24743
Matched 362293 24744
Matched 362293 24745
Matched 362293 24746
Matched 362292 24747
Matched 362292 24748
Matched 362199 24749
Matched 362199 24750
Matched 362196 24751
Matched 362196 24752
Matched 362196 24753
Matched 362196 24754
Matched 362133 24755
Matched 362133 24756
Matched 362093 24757
Matched 362093 24758
Matched 362093 24759
Matched 362093 24760
Matched 361859 24761
Matched 361859 24762
Matched 361834 24763
Matched 361834 24764
Matched 361834 24765
Matched 361834 24766
Matched 361834 24767
Matched 361834 24768
Matched 361770 24769
Matched 361770 24770
Matched 361770 24771
Matched 361770 24772
Matched 361770 24773
Matched 361770 24774
Matched 361770 24775
Matched 361770 24776
Matched 361770 24777
Matched 361770 24778
Matched 361770 24779
Matched 361770 24780
Matched 361770 24781
Matched 361770 24782
Matched 361770 24783
Matched 361770 24784
Matched 361770 24785
Matched 361770 24786
Matched 361770 24787
Matched 361770 24788
Matched 361762 24789
Matched 361762 24790
Matched 361762 24791
Matched 361762 24792
Matched 361762 24793
Matched 361762 24794
Matched 361762 24795
Matched 361762 24796
Matched 361762 24797
Matched 361762 24798
Matched 361762 24799
Matched 361762 24800
Matched 361762 24801
Matched 361762 24802
Matched 361762 24803
Matched 361762 24804
Matched 361762 24805
Matched 361762 24806
Matched 361762 24807
Matched 361757 24808
Matched 361757 24809
Matched 361757 24810
Matched 361757 24811
Matched 361757 24812
Matched 361757 24813
Matched 361757 24814
Matched 361757 24815
Matched 361757 24816
Matched 361757 24817
Matched 361757 24818
Matched 361757 24819
Matched 361757 24820
Matched 361757 24821
Matched 361734 24822
Matched 361734 24823
Matched 361727 24824
Matched 361727 24825
Matched 361727 24826
Matched 361727 24827
Matched 361722 24828
Matched 361722 24829
Matched 361722 24830
Matched 361722 24831
Matched 361718 24832
Matched 361718 24833
Matched 361627 24834
Matched 361627 24835
Matched 361393 24836
Matched 361393 24837
Matched 361393 24838
Matched 361388 24839
Matched 361388 24840
Matched 361388 24841
Matched 361388 24842
Matched 361387 24843
Matched 361387 24844
Matched 361387 24845
Matched 361387 24846
Matched 361384 24847
Matched 361384 24848
Matched 361384 24849
Matched 361384 24850
Matched 361384 24851
Matched 361384 24852
Matched 361384 24853
Matched 361384 24854
Matched 361384 24855
Matched 361384 24856
Matched 361384 24857
Matched 361384 24858
Matched 361384 24859
Matched 361384 24860
Matched 361384 24861
Matched 361384 24862
Matched 361384 24863
Matched 361384 24864
Matched 361384 24865
Matched 361384 24866
Matched 361379 24867
Matched 361379 24868
Matched 361379 24869
Matched 361379 24870
Matched 361379 24871
Matched 361379 24872
Matched 361379 24873
Matched 361379 24874
Matched 361212 24875
Matched 361212 24876
Matched 361212 24877
Matched 361212 24878
Matched 361212 24879
Matched 361212 24880
Matched 361212 24881
Matched 361212 24882
Matched 361212 24883
Matched 361212 24884
Matched 361212 24885
Matched 361212 24886
Matched 361212 24887
Matched 361212 24888
Matched 361212 24889
Matched 361212 24890
Matched 361212 24891
Matched 361212 24892
Matched 361212 24893
Matched 361212 24894
Matched 360991 24895
Matched 360991 24896
Matched 360991 24897
Matched 360991 24898
Matched 360991 24899
Matched 360991 24900
Matched 360991 24901
Matched 360991 24902
Matched 360991 24903
Matched 360991 24904
Matched 360991 24905
Matched 360990 24906
Matched 360990 24907
Matched 360990 24908
Matched 360990 24909
Matched 360990 24910
Matched 360990 24911
Matched 360990 24912
Matched 360990 24913
Matched 360971 24914
Matched 360971 24915
Matched 360970 24916
Matched 360970 24917
Matched 360964 24918
Matched 360964 24919
Matched 360964 24920
Matched 360964 24921
Matched 360963 24922
Matched 360963 24923
Matched 360963 24924
Matched 360963 24925
Matched 360963 24926
Matched 360963 24927
Matched 360963 24928
Matched 360956 24929
Matched 360956 24930
Matched 360956 24931
Matched 360793 24932
Matched 360793 24933
Matched 360793 24934
Matched 360790 24935
Matched 360790 24936
Matched 360790 24937
Matched 360790 24938
Matched 360790 24939
Matched 360790 24940
Matched 360790 24941
Matched 360790 24942
Matched 360790 24943
Matched 360220 24944
Matched 360220 24945
Matched 360190 24946
Matched 360190 24947
Matched 359903 24948
Matched 359903 24949
Matched 359903 24950
Matched 359883 24951
Matched 359883 24952
Matched 359880 24953
Matched 359880 24954
Matched 359880 24955
Matched 359880 24956
Matched 359880 24957
Matched 359880 24958
Matched 359753 24959
Matched 359753 24960
Matched 359753 24961
Matched 359504 24962
Matched 359504 24963
Matched 359504 24964
Matched 359287 24965
Matched 359287 24966
Matched 359089 24967
Matched 359089 24968
Matched 359089 24969
Matched 359089 24970
Matched 359087 24971
Matched 359087 24972
Matched 359087 24973
Matched 359087 24974
Matched 358669 24975
Matched 358669 24976
Matched 358669 24977
Matched 358667 24978
Matched 358667 24979
Matched 358667 24980
Matched 358667 24981
Matched 358667 24982
Matched 358667 24983
Matched 358667 24984
Matched 358667 24985
Matched 358667 24986
Matched 358667 24987
Matched 358667 24988
Matched 358667 24989
Matched 358666 24990
Matched 358666 24991
Matched 358666 24992
Matched 358666 24993
Matched 358666 24994
Matched 358666 24995
Matched 358631 24996
Matched 358631 24997
Matched 358477 24998
Matched 358477 24999
Matched 358477 25000
Matched 358477 25001
Matched 358477 25002
Matched 358477 25003
Matched 358450 25004
Matched 358450 25005
Matched 358450 25006
Matched 358437 25007
Matched 358437 25008
Matched 358437 25009
Matched 358437 25010
Matched 358434 25011
Matched 358434 25012
Matched 358401 25013
Matched 358401 25014
Matched 358401 25015
Matched 358401 25016
Matched 358401 25017
Matched 358358 25018
Matched 358358 25019
Matched 358358 25020
Matched 358182 25021
Matched 358182 25022
Matched 358182 25023
Matched 358182 25024
Matched 358182 25025
Matched 358110 25026
Matched 358110 25027
Matched 358032 25028
Matched 358032 25029
Matched 358032 25030
Matched 358032 25031
Matched 358032 25032
Matched 358032 25033
Matched 358032 25034
Matched 358028 25035
Matched 358028 25036
Matched 358028 25037
Matched 358028 25038
Matched 358020 25039
Matched 358020 25040
Matched 357934 25041
Matched 357934 25042
Matched 357934 25043
Matched 357764 25044
Matched 357764 25045
Matched 357561 25046
Matched 357561 25047
Matched 357561 25048
Matched 357561 25049
Matched 357560 25050
Matched 357560 25051
Matched 357560 25052
Matched 357559 25053
Matched 357559 25054
Matched 357559 25055
Matched 357559 25056
Matched 357523 25057
Matched 357523 25058
Matched 357522 25059
Matched 357522 25060
Matched 357522 25061
Matched 357387 25062
Matched 357387 25063
Matched 357387 25064
Matched 357387 25065
Matched 357387 25066
Matched 357387 25067
Matched 357387 25068
Matched 357387 25069
Matched 357385 25070
Matched 357385 25071
Matched 357385 25072
Matched 357385 25073
Matched 357367 25074
Matched 357367 25075
Matched 357355 25076
Matched 357355 25077
Matched 357197 25078
Matched 357197 25079
Matched 357197 25080
Matched 357197 25081
Matched 357147 25082
Matched 357147 25083
Matched 357147 25084
Matched 357147 25085
Matched 357117 25086
Matched 357117 25087
Matched 357117 25088
Matched 357117 25089
Matched 357117 25090
Matched 357117 25091
Matched 357117 25092
Matched 357117 25093
Matched 357117 25094
Matched 357117 25095
Matched 357117 25096
Matched 357114 25097
Matched 357114 25098
Matched 357112 25099
Matched 357112 25100
Matched 357111 25101
Matched 357111 25102
Matched 357111 25103
Matched 357111 25104
Matched 357111 25105
Matched 357111 25106
Matched 357110 25107
Matched 357110 25108
Matched 357110 25109
Matched 357110 25110
Matched 357110 25111
Matched 357110 25112
Matched 357110 25113
Matched 357095 25114
Matched 357095 25115
Matched 357095 25116
Matched 357095 25117
Matched 357095 25118
Matched 357095 25119
Matched 357095 25120
Matched 357095 25121
Matched 357082 25122
Matched 357082 25123
Matched 357082 25124
Matched 356996 25125
Matched 356996 25126
Matched 356996 25127
Matched 356996 25128
Matched 356996 25129
Matched 356994 25130
Matched 356994 25131
Matched 356994 25132
Matched 356993 25133
Matched 356993 25134
Matched 356992 25135
Matched 356949 25136
Matched 356949 25137
Matched 356949 25138
Matched 356949 25139
Matched 356948 25140
Matched 356948 25141
Matched 356947 25142
Matched 356947 25143
Matched 356889 25144
Matched 356889 25145
Matched 356881 25146
Matched 356881 25147
Matched 356881 25148
Matched 356881 25149
Matched 356881 25150
Matched 356881 25151
Matched 356881 25152
Matched 356881 25153
Matched 356881 25154
Matched 356881 25155
Matched 356881 25156
Matched 356881 25157
Matched 356879 25158
Matched 356879 25159
Matched 356879 25160
Matched 356869 25161
Matched 356869 25162
Matched 356869 25163
Matched 356866 25164
Matched 356866 25165
Matched 356866 25166
Matched 356860 25167
Matched 356856 25168
Matched 356856 25169
Matched 356855 25170
Matched 356855 25171
Matched 356848 25172
Matched 356838 25173
Matched 356838 25174
Matched 356753 25175
Matched 356753 25176
Matched 356753 25177
Matched 356753 25178
Matched 356753 25179
Matched 356753 25180
Matched 356740 25181
Matched 356740 25182
Matched 356740 25183
Matched 356740 25184
Matched 356740 25185
Matched 356740 25186
Matched 356738 25187
Matched 356738 25188
Matched 356738 25189
Matched 356738 25190
Matched 356661 25191
Matched 356661 25192
Matched 356661 25193
Matched 356655 25194
Matched 356655 25195
Matched 356655 25196
Matched 356655 25197
Matched 356655 25198
Matched 356655 25199
Matched 356655 25200
Matched 356655 25201
Matched 356610 25202
Matched 356610 25203
Matched 356610 25204
Matched 356609 25205
Matched 356609 25206
Matched 356609 25207
Matched 356579 25208
Matched 356579 25209
Matched 356579 25210
Matched 356578 25211
Matched 356578 25212
Matched 356578 25213
Matched 356569 25214
Matched 356569 25215
Matched 356567 25216
Matched 356567 25217
Matched 356567 25218
Matched 356567 25219
Matched 356503 25220
Matched 356503 25221
Matched 356503 25222
Matched 356503 25223
Matched 356503 25224
Matched 356503 25225
Matched 356503 25226
Matched 356503 25227
Matched 356502 25228
Matched 356502 25229
Matched 356501 25230
Matched 356501 25231
Matched 356501 25232
Matched 356501 25233
Matched 356501 25234
Matched 356501 25235
Matched 356501 25236
Matched 356501 25237
Matched 356501 25238
Matched 356498 25239
Matched 356498 25240
Matched 356498 25241
Matched 356498 25242
Matched 356498 25243
Matched 356498 25244
Matched 356498 25245
Matched 356498 25246
Matched 356498 25247
Matched 356498 25248
Matched 356498 25249
Matched 356498 25250
Matched 356491 25251
Matched 356491 25252
Matched 356491 25253
Matched 356491 25254
Matched 356491 25255
Matched 356491 25256
Matched 356491 25257
Matched 356491 25258
Matched 356488 25259
Matched 356488 25260
Matched 356471 25261
Matched 356471 25262
Matched 356471 25263
Matched 356471 25264
Matched 356471 25265
Matched 356471 25266
Matched 356471 25267
Matched 356471 25268
Matched 356471 25269
Matched 356471 25270
Matched 356471 25271
Matched 356432 25272
Matched 356432 25273
Matched 356335 25274
Matched 356335 25275
Matched 356335 25276
Matched 356013 25277
Matched 356013 25278
Matched 356013 25279
Matched 356013 25280
Matched 356004 25281
Matched 356004 25282
Matched 356004 25283
Matched 356004 25284
Matched 356004 25285
Matched 356004 25286
Matched 356004 25287
Matched 356004 25288
Matched 355958 25289
Matched 355958 25290
Matched 355645 25291
Matched 355645 25292
Matched 355580 25293
Matched 355580 25294
Matched 355580 25295
Matched 355580 25296
Matched 355580 25297
Matched 355580 25298
Matched 355580 25299
Matched 355580 25300
Matched 355580 25301
Matched 355580 25302
Matched 355580 25303
Matched 355580 25304
Matched 355580 25305
Matched 355579 25306
Matched 355579 25307
Matched 355579 25308
Matched 355579 25309
Matched 355579 25310
Matched 355579 25311
Matched 355579 25312
Matched 355306 25313
Matched 355306 25314
Matched 355306 25315
Matched 355306 25316
Matched 355306 25317
Matched 355306 25318
Matched 355306 25319
Matched 355306 25320
Matched 355306 25321
Matched 355306 25322
Matched 355306 25323
Matched 355282 25324
Matched 355282 25325
Matched 355282 25326
Matched 355282 25327
Matched 355282 25328
Matched 355282 25329
Matched 355282 25330
Matched 355007 25331
Matched 355007 25332
Matched 354798 25333
Matched 354798 25334
Matched 354798 25335
Matched 354798 25336
Matched 354798 25337
Matched 354791 25338
Matched 354791 25339
Matched 354791 25340
Matched 354791 25341
Matched 354791 25342
Matched 354791 25343
Matched 354790 25344
Matched 354790 25345
Matched 354790 25346
Matched 354790 25347
Matched 354788 25348
Matched 354788 25349
Matched 354788 25350
Matched 354788 25351
Matched 354788 25352
Matched 354781 25353
Matched 354781 25354
Matched 354781 25355
Matched 354781 25356
Matched 354781 25357
Matched 354781 25358
Matched 354781 25359
Matched 354781 25360
Matched 354781 25361
Matched 354781 25362
Matched 354781 25363
Matched 354781 25364
Matched 354781 25365
Matched 354781 25366
Matched 354781 25367
Matched 354779 25368
Matched 354779 25369
Matched 354779 25370
Matched 354779 25371
Matched 354779 25372
Matched 354779 25373
Matched 354779 25374
Matched 354779 25375
Matched 354779 25376
Matched 354779 25377
Matched 354779 25378
Matched 354779 25379
Matched 354774 25380
Matched 354774 25381
Matched 354774 25382
Matched 354774 25383
Matched 354774 25384
Matched 354774 25385
Matched 354774 25386
Matched 354774 25387
Matched 354774 25388
Matched 354774 25389
Matched 354774 25390
Matched 354774 25391
Matched 354774 25392
Matched 354774 25393
Matched 354755 25394
Matched 354755 25395
Matched 354746 25396
Matched 354746 25397
Matched 354746 25398
Matched 354746 25399
Matched 354744 25400
Matched 354744 25401
Matched 354744 25402
Matched 354744 25403
Matched 354744 25404
Matched 354743 25405
Matched 354743 25406
Matched 354743 25407
Matched 354743 25408
Matched 354741 25409
Matched 354741 25410
Matched 354741 25411
Matched 354741 25412
Matched 354741 25413
Matched 354741 25414
Matched 354741 25415
Matched 354741 25416
Matched 354741 25417
Matched 354740 25418
Matched 354740 25419
Matched 354740 25420
Matched 354740 25421
Matched 354740 25422
Matched 354740 25423
Matched 354740 25424
Matched 354740 25425
Matched 354738 25426
Matched 354738 25427
Matched 354738 25428
Matched 354738 25429
Matched 354738 25430
Matched 354737 25431
Matched 354737 25432
Matched 354737 25433
Matched 354737 25434
Matched 354737 25435
Matched 354737 25436
Matched 354737 25437
Matched 354737 25438
Matched 354736 25439
Matched 354736 25440
Matched 354736 25441
Matched 354736 25442
Matched 354736 25443
Matched 354736 25444
Matched 354736 25445
Matched 354736 25446
Matched 354736 25447
Matched 354736 25448
Matched 354736 25449
Matched 354736 25450
Matched 354736 25451
Matched 354735 25452
Matched 354735 25453
Matched 354735 25454
Matched 354735 25455
Matched 354735 25456
Matched 354735 25457
Matched 354735 25458
Matched 354735 25459
Matched 354733 25460
Matched 354733 25461
Matched 354733 25462
Matched 354733 25463
Matched 354733 25464
Matched 354733 25465
Matched 354733 25466
Matched 354730 25467
Matched 354730 25468
Matched 354730 25469
Matched 354730 25470
Matched 354730 25471
Matched 354729 25472
Matched 354729 25473
Matched 354726 25474
Matched 354726 25475
Matched 354726 25476
Matched 354726 25477
Matched 354719 25478
Matched 354719 25479
Matched 354719 25480
Matched 354719 25481
Matched 354705 25482
Matched 354705 25483
Matched 354705 25484
Matched 354705 25485
Matched 354705 25486
Matched 354705 25487
Matched 354386 25488
Matched 354386 25489
Matched 354386 25490
Matched 354386 25491
Matched 354386 25492
Matched 354384 25493
Matched 354384 25494
Matched 354355 25495
Matched 354355 25496
Matched 354288 25497
Matched 354288 25498
Matched 354288 25499
Matched 354237 25500
Matched 354237 25501
Matched 354237 25502
Matched 354237 25503
Matched 354214 25504
Matched 354214 25505
Matched 354214 25506
Matched 354214 25507
Matched 354172 25508
Matched 354172 25509
Matched 354171 25510
Matched 354171 25511
Matched 354171 25512
Matched 354171 25513
Matched 354171 25514
Matched 354171 25515
Matched 354170 25516
Matched 354170 25517
Matched 354159 25518
Matched 354159 25519
Matched 354159 25520
Matched 354159 25521
Matched 354159 25522
Matched 354159 25523
Matched 354159 25524
Matched 354159 25525
Matched 354159 25526
Matched 354145 25527
Matched 354145 25528
Matched 354145 25529
Matched 354145 25530
Matched 354145 25531
Matched 354145 25532
Matched 354053 25533
Matched 354053 25534
Matched 354047 25535
Matched 354047 25536
Matched 354047 25537
Matched 354047 25538
Matched 354046 25539
Matched 354046 25540
Matched 354041 25541
Matched 354041 25542
Matched 354041 25543
Matched 354028 25544
Matched 354028 25545
Matched 354028 25546
Matched 354028 25547
Matched 354028 25548
Matched 354015 25549
Matched 354015 25550
Matched 354015 25551
Matched 354015 25552
Matched 354015 25553
Matched 353764 25554
Matched 353764 25555
Matched 353764 25556
Matched 353764 25557
Matched 353764 25558
Matched 353604 25559
Matched 353604 25560
Matched 353604 25561
Matched 353604 25562
Matched 353604 25563
Matched 353604 25564
Matched 353604 25565
Matched 353604 25566
Matched 353604 25567
Matched 353604 25568
Matched 353604 25569
Matched 353604 25570
Matched 353604 25571
Matched 353604 25572
Matched 353604 25573
Matched 353604 25574
Matched 353604 25575
Matched 353604 25576
Matched 353604 25577
Matched 353604 25578
Matched 353604 25579
Matched 353604 25580
Matched 353604 25581
Matched 353603 25582
Matched 353603 25583
Matched 353603 25584
Matched 353553 25585
Matched 353553 25586
Matched 353524 25587
Matched 353524 25588
Matched 353511 25589
Matched 353511 25590
Matched 353511 25591
Matched 353460 25592
Matched 353460 25593
Matched 353430 25594
Matched 353430 25595
Matched 353430 25596
Matched 353430 25597
Matched 353414 25598
Matched 353414 25599
Matched 353377 25600
Matched 353377 25601
Matched 353377 25602
Matched 353377 25603
Matched 353365 25604
Matched 353365 25605
Matched 353365 25606
Matched 353365 25607
Matched 353230 25608
Matched 353230 25609
Matched 353230 25610
Matched 353230 25611
Matched 353230 25612
Matched 353230 25613
Matched 353230 25614
Matched 353230 25615
Matched 353230 25616
Matched 353230 25617
Matched 353230 25618
Matched 353230 25619
Matched 353230 25620
Matched 353230 25621
Matched 353230 25622
Matched 353230 25623
Matched 353230 25624
Matched 353230 25625
Matched 353230 25626
Matched 353230 25627
Matched 353230 25628
Matched 353230 25629
Matched 353230 25630
Matched 353230 25631
Matched 353230 25632
Matched 353230 25633
Matched 353230 25634
Matched 353230 25635
Matched 353230 25636
Matched 353214 25637
Matched 353214 25638
Matched 353181 25639
Matched 353181 25640
Matched 353181 25641
Matched 353134 25642
Matched 353134 25643
Matched 353118 25644
Matched 353118 25645
Matched 353118 25646
Matched 353099 25647
Matched 353099 25648
Matched 353085 25649
Matched 353085 25650
Matched 353053 25651
Matched 353053 25652
Matched 352920 25653

In [76]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39183,14476 https://www.storeakmedia.com/storeak-...,332027,14476 كونسيلر فوري مضاد للشيخوخة 6 ملمنير ...,14476 Instant Anti Age Eraser Concealer 6 m...,14476 3600531396831 14477 3600530733842 ...,NAN,14476 17250 14477 17250 14478 17250 1...,8254 كونسيلر مصحح بخصائص مضادة للشيخوخة تخ...,8254 A corrective concealer with anti agin...,"8254 المكياج‎ -> الوجه‎ -> كونسيلر & مصحح,...",8254 ...,8254 ...,False
39184,14482 https://www.storeakmedia.com/storeak-...,316612,14482 غسول الفم للثة الصحية بالنعناع النقي...,14482 Healthy Gums Mouthwash Pure Mint500 ...,14482 697029058770 14483 697029602478 Na...,NAN,"14482 17000 14483 6500 Name: Price, dty...",23139 غسول الفم والاسنان لتقليل نزيف والتها...,23139 Mouthwash and teeth to reduce bleedin...,23139 العناية بالبشرة‎ -> العناية بالفم‎ ->...,"23139 ثيرابريث Name: Brand, dtype: object","23139 TheraBreath Name: Secondary Brand, dt...",False
39185,14482 https://www.storeakmedia.com/storeak-...,316612,14482 غسول الفم للثة الصحية بالنعناع النقي...,14482 Healthy Gums Mouthwash Pure Mint500 ...,14482 697029058770 14483 697029602478 Na...,NAN,"14482 17000 14483 6500 Name: Price, dty...",23139 غسول الفم والاسنان لتقليل نزيف والتها...,23139 Mouthwash and teeth to reduce bleedin...,23139 العناية بالبشرة‎ -> العناية بالفم‎ ->...,23139 ث...,23139 ...,False
39186,14484 ...,316610,14484 غسول فم منعش بالنعناع الخفيف500 مل 1...,14484 Fresh Breath Oral Rinse Mild Mint500...,14484 697029041260 14485 697029532409 Na...,NAN,"14484 17000 14485 6500 Name: Price, dty...",23141 غسول الفم والاسنان يعمل على تحييد الب...,23141 Mouthwash neutralizes sulfur producin...,23141 العناية بالبشرة‎ -> العناية بالفم‎ ->...,"23141 ذا بريث كو Name: Brand, dtype: object","23141 The Breath.Co Name: Secondary Brand, ...",False
39187,14484 ...,316610,14484 غسول فم منعش بالنعناع الخفيف500 مل 1...,14484 Fresh Breath Oral Rinse Mild Mint500...,14484 697029041260 14485 697029532409 Na...,NAN,"14484 17000 14485 6500 Name: Price, dty...",23141 غسول الفم والاسنان يعمل على تحييد الب...,23141 Mouthwash neutralizes sulfur producin...,23141 العناية بالبشرة‎ -> العناية بالفم‎ ->...,23141 ذ...,23141 T...,False

In [ ]:
dfItems.to_csv("FinalItems.csv",index=False)