In [4]:
import pandas as pd

In [98]:
#Series

In [99]:
sr = pd.Series(["Ahmad","Python","Class"],index=["*","=>","!"])

In [100]:
sr

*      Ahmad
=>    Python
!      Class
dtype: object

In [101]:
userData = {"name":["Ahmad","python","Class"],"age":[25,26,27]}

In [102]:
userData

{'name': ['Ahmad', 'python', 'Class'], 'age': [25, 26, 27]}

In [103]:
df = pd.DataFrame(userData)

In [104]:
df

     name  age
0   Ahmad   25
1  python   26
2   Class   27

In [105]:
df.to_csv("ClasFirstTable.csv")

In [5]:
dfItems = pd.read_excel("/Users/muhammadahmadhumayoun/Downloads/GithubTutorial/AdvancePythonClass/AdvancePythonClassRepo/PandasTabularData/VendorProducts.xlsx",sheet_name="Items")
dfCollections= pd.read_excel("/Users/muhammadahmadhumayoun/Downloads/GithubTutorial/AdvancePythonClass/AdvancePythonClassRepo/PandasTabularData/VendorProducts.xlsx",sheet_name="Collections")

In [107]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [108]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [109]:
print(type(dfItems))
print(type(dfItems["Secondary Description"]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [110]:
#Name
#Price
#Brand
#Barcode

In [111]:
dfItems["Price"]

0         25,000د.ع
1        300,000د.ع
2         30,000د.ع
3             00د.ع
4         15,000د.ع
            ...
24697     16,500د.ع
24698     12,000د.ع
24699     10,500د.ع
24700     15,000د.ع
24701     22,500د.ع
Name: Price, Length: 24702, dtype: object

In [112]:
x =" 25,000د.ع"
25000

25000

In [113]:
dfItems.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24702 entries, 0 to 24701
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Picture                    24300 non-null  object
 1   Id                         24702 non-null  int64
 2   Name                       24702 non-null  object
 3   Secondary Name             24702 non-null  object
 4   Barcode                    22041 non-null  object
 5   Code                       21993 non-null  object
 6   Price                      24702 non-null  object
 7   Description                24645 non-null  object
 8   Secondary Description      24644 non-null  object
 9   Sub Description            24601 non-null  object
 10  Secondary Sub Description  4 non-null      object
 11  Menu                       24699 non-null  object
 12  Brand                      24699 non-null  object
 13  Secondary Brand            24696 non-null  object
 14  Has Collections            24702 non-null  object
dtypes: int64(1), object(14)
memory usage: 2.8+ MB

In [114]:
dfItems.describe()

                  Id
count   24702.000000
mean   330583.440936
std     12701.598678
min    314991.000000
25%    321257.250000
50%    327496.500000
75%    334544.750000
max    390188.000000

In [115]:
dfItems.head()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No

In [116]:
dfItems.tail()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [117]:
dfItems.fillna("")

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,,,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [118]:
dfItems[["Name"]].fillna("")

                                                   Name
0                            زيت الشفاه بليجر 001، 5 مل
1                  عطر بلو دي شانيل لي اكسكلوسيف الجديد
2                 سيروم الشعر لفروة الرأس سيابوري 20 مل
3                        عطر جانيميد اودي بارفيوم 50 مل
4                   جل تصفيف الحواجب مع الببتيدات 15 مل
...                                                 ...
24697        معطر الشعر والجسم بالليمون والماتشا 150 مل
24698  معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل
24699         ماسكارا جلام اند دول تعزز نمو الرموش 8 مل
24700                        مست الجسم باشن فروت 150 مل
24701               ماسكارا فائقة الكثافة (1أسود) 15 مل

[24702 rows x 1 columns]

In [119]:
#Make a data Frame of UserName /  Age / Class
# Save file as userData.csv

In [120]:
UserDataDictionary = {"Name":["Ahmad","Python","Class"],"Age":[25,26,27],"Class":["A","B","C"]}

In [121]:
df = pd.DataFrame(UserDataDictionary)

In [122]:
df.to_csv("UserData.csv",index=False)

In [123]:
UserDF = pd.read_csv("UserData.csv")

In [124]:
UserDF

     Name  Age Class
0   Ahmad   25     A
1  Python   26     B
2   Class   27     C

In [125]:
currentrowNumber = len(UserDF["Name"])
UserDF.loc[currentrowNumber] = ["Ali","25","A"]

In [126]:
UserDF1 = UserDF

In [127]:
UserDF1.to_csv("UserData.csv",index=False)

In [128]:
UserDF1

     Name Age Class
0   Ahmad  25     A
1  Python  26     B
2   Class  27     C
3     Ali  25     A

In [129]:
# Create banking System
# Ask user to Create Account or Check or withDraw or deposit
# Use while true for this process
# Lets say user created account = 5000
# Dictionary Example = {"UserNames":[a,b,c,d,e],"Age":[1,2,3,4],"Balance":[1000,2000,3000,4000]
#Create a csv and store data in therep

In [130]:
"""
Create a Simple Banking System in Python that stores account data in a CSV file using the Pandas library. The program should be menu-driven and continuously run until the user chooses to exit. The CSV file should contain the columns AccountNumber, Name, and Balance. The program must support the following operations:
	1.	Create Account – Ask the user for account number, customer name, and initial balance, then store the record in the CSV file.
	2.	Deposit Money – Ask for account number and deposit amount, find the account, and increase the balance.
	3.	Withdraw Money – Ask for account number and withdrawal amount, check if the account has sufficient balance, and subtract the amount if possible. If not, display “Insufficient Balance.”
	4.	Check Balance – Ask for the account number and display the current balance of that account.
	5.	Exit – Terminate the program when the user selects this option.

The program should read data from the CSV file, update it when transactions occur, and save the updated data back to the file.
"""

'\nCreate a Simple Banking System in Python that stores account data in a CSV file using the Pandas library. The program should be menu-driven and continuously run until the user chooses to exit. The CSV file should contain the columns AccountNumber, Name, and Balance. The program must support the following operations:\n\t1.\tCreate Account – Ask the user for account number, customer name, and initial balance, then store the record in the CSV file.\n\t2.\tDeposit Money – Ask for account number and deposit amount, find the account, and increase the balance.\n\t3.\tWithdraw Money – Ask for account number and withdrawal amount, check if the account has sufficient balance, and subtract the amount if possible. If not, display “Insufficient Balance.”\n\t4.\tCheck Balance – Ask for the account number and display the current balance of that account.\n\t5.\tExit – Terminate the program when the user selects this option.\n\nThe program should read data from the CSV file, update it when transactions occur, and save the updated data back to the file.\n'

In [153]:
import random as rd
while True:
    choice = int(input("Enter 1 for account Opening \n Enter 2 for Balance Check \n Enter 3 for WithDrawl \n Enter 4 for Deposit: \n Enter 5 for Exit:"))
    if choice ==1:
        userDB = pd.read_csv("Bank.csv")
        userName = input("Enter User Name:")
        accNo = rd.randint(10000,99999)
        balance = 5000
        newUserDataList = [accNo,userName,balance]
        currentrowNumber = len(userDB["AccountNumber"])
        userDB.loc[currentrowNumber] = newUserDataList
        userDB.to_csv("Bank.csv",index=False)
        print("Account Created")
    elif choice ==2:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                print(f"Welcome {nm} \nYour Balance is {userDB['Balance'][i]}")

    elif choice ==3:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                amount2Wtihdraw = int(input("Enter Amount to Withdraw:"))
                userDB['Balance'][i] = userDB['Balance'][i] - amount2Wtihdraw
                # userDB['Balance'][i] = newBalance
                print(f"Welcome {nm} \nYour new Balance is {userDB['Balance'][i]}")
                userDB.to_csv("Bank.csv",index=False)
    elif choice ==4:
        userDB = pd.read_csv("Bank.csv")
        accNo = int(input("Enter Account Number:"))
        if accNo not in list(userDB["AccountNumber"]):
            print("Account Number Not Found")
            continue
        for i in range(len(userDB)):
            if userDB["AccountNumber"][i] == accNo:
                nm = userDB["FullName"][i]
                amount2Wtihdraw = int(input("Enter Amount to Withdraw:"))
                userDB['Balance'][i] = userDB['Balance'][i] + amount2Wtihdraw
                # userDB['Balance'][i] = newBalance
                print(f"Welcome {nm} \nYour new Balance is {userDB['Balance'][i]}")
                userDB.to_csv("Bank.csv",index=False)
    elif choice ==5:
        print("Exiting")
        break

Account Created
Exiting

In [151]:
userDictionary = {"AccountNumber":[10001],"FullName":["Ahmad"],"Balance":[5000]}
df = pd.DataFrame(userDictionary)
df

   AccountNumber FullName  Balance
0          10001    Ahmad     5000

In [152]:
df.to_csv("Bank.csv",index=False)

In [1]:
"""
user id = string
username = string
class = sstring
subjects = list


Student registration
Student information fetch
student information update
"""

'\nuser id = string\nusername = string\nclass = sstring\nsubjects = list\n\n\nStudent registration\nStudent information fetch\nstudent information update\n'

In [2]:
import pandas as pd

In [17]:
StudentAccountDictionary = {"StudentId":["10001","10002","10003"],"StudentName":["Ahmad","Ali","yth"],"StudentClass":["1","2","3"],"Subjects":[["Math","English","Science"],["Math","Chemistry","Science"],["islamicStudies","English","Physics"]]}

In [18]:
studentDF = pd.DataFrame(StudentAccountDictionary)

In [19]:
studentDF

  StudentId StudentName StudentClass                            Subjects
0     10001       Ahmad            1            [Math, English, Science]
1     10002         Ali            2          [Math, Chemistry, Science]
2     10003         yth            3  [islamicStudies, English, Physics]

In [20]:
studentDF.to_csv("StudentData.csv",index=False)

In [3]:
import random as r
while True:
    choice = input("Enter 1 for Student Registration \n Enter 2 for Student Information Fetch \n Enter 3 for Student Information Update \n Enter 4 for Exit:")
    if choice == "1":
        print("======Registering Student========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = r.randint(10000,99999)
        studentName = input("Enter Student Name:")
        studentClass = input("Enter Student Class:")
        subjects = ["Maths","English","Science"]
        currentrowNumber = len(studentDF["StudentId"])
        studentDF.loc[currentrowNumber] = [studentId,studentName,studentClass,subjects]
        studentDF.to_csv("StudentData.csv",index=False)

        print("======Registering Student========")

    elif choice =="2":
        print("======Student Information Fetch========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print(f"Student Name : {studentDF['StudentName'][i]}")
                print(f"Student Class : {studentDF['StudentClass'][i]}")
                print(f"Student Subjects : {studentDF['Subjects'][i]}")
        print("======Student Information Fetch========")
    elif choice =="3":
        print("======Student Information Update=======")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print("What do you want to update?")
                updateChoice = input("Enter 1 for Student Name \n Enter 2 for Student Class \n Enter 3 for Student Subjects:")
                if updateChoice == "1":
                    newStudentName = input("Enter New Student Name:")
                    studentDF['StudentName'][i] = newStudentName
                    print(f"Student Name Updated to {newStudentName}")
                elif updateChoice == "2":
                    newStudentClass = input("Enter New Student Class:")
                    studentDF['StudentClass'][i] = newStudentClass
                    print(f"Student Class Updated to {newStudentClass}")
                elif updateChoice == "3":
                    subjectsChoice = input("Do you want to add subjects or remove subjects? Enter 1 for Add \n Enter 2 for Remove:")
                    if subjectsChoice == "1":
                        newSubjects = input("Enter New Subjects:")
                        studentDF['Subjects'][i].append(newSubjects)
                        print(f"Student Subjects Updated to {studentDF['Subjects'][i]}")
                    if subjectsChoice == "2":
                        subjectsToRemove = input("Enter Subjects to Remove:")
                        studentDF['Subjects'][i].remove(subjectsToRemove)
        print("======Student Information Update=======")
    elif choice =="4":
        print("Exiting")
        break

======Registering Student========
======Registering Student========
Exiting

In [18]:
dfItems.loc(0)

                                       Secondary Name       Price
1                    Bleu De Chanel L'Exclusif Parfum  300,000د.ع
2                     Seapuri Scalpy Hair Serum 20 ml   30,000د.ع
3                                  Ganymede EDP 50 ml       00د.ع
4               Brow Styling Gel With Peptides 15 ml    15,000د.ع
5                             Limitless Mascara 10 ml   15,000د.ع
6                                  Eyebrow Serum 5 ml   18,000د.ع
7                               Evadamo Mascara 10 ml   15,000د.ع
8                        Argan Oil Conditioner 300 ml    7,750د.ع
9                       Argan Oil Conditioner 1000 ml   15,500د.ع
10  Professional 1500 W Hair Dryer With 7 Attachments   65,000د.ع

In [37]:
questionare=pd.read_csv("QuestionareDummy.csv")

In [38]:
questionare

,Question,Option A,Option B,Option C,Option D,Right Answer
0,Which programming language is known as the 'mo...,Python,C,Java,Assembly,B
1,What is the chemical symbol for Gold?,Gd,Ag,Au,Go,C
2,Which planet is known as the Red Planet?,Venus,Mars,Jupiter,Saturn,B
3,What does 'CPU' stand for?,Central Processing Unit,Control Programming Unit,Computer Personal Unit,Central Print Utility,A
4,Which ocean is the largest on Earth?,Atlantic Ocean,Indian Ocean,Arctic Ocean,Pacific Ocean,D
5,"In Python, which library is commonly used for ...",NumPy,Pandas,Matplotlib,PyQt,B
6,Who painted the Mona Lisa?,Vincent van Gogh,Pablo Picasso,Leonardo da Vinci,Claude Monet,C
7,What is the capital city of Japan?,Seoul,Beijing,Bangkok,Tokyo,D
8,Which component is responsible for long-term d...,RAM,CPU,HDD/SSD,GPU,C
9,What is the square root of 144?,10,12,14,16,B
10,Which gas do plants primarily absorb for photo...,Oxygen,Nitrogen,Carbon Dioxide,Hydrogen,C
11,"In Unity, which file extension is used for C# ...",.unity,.cpp,.js,.cs,D
12,What is the powerhouse of the cell?,Nucleus,Ribosome,Mitochondria,Cytoplasm,C
13,Which country is the largest by land area?,USA,China,Russia,Canada,C
14,What is the value of Pi rounded to two decimal...,3.12,3.14,3.16,3.18,B
15,Who is credited with inventing the World Wide ...,Steve Jobs,Bill Gates,Tim Berners-Lee,Elon Musk,C
16,Which element has the atomic number 1?,Helium,Oxygen,Hydrogen,Carbon,C
17,What is the currency of the United Kingdom?,Euro,Dollar,Pound Sterling,Yen,C
18,Which year did the Titanic sink?,1905,1912,1918,1924,B
19,"Which data structure follows the 'Last-In, Fir...",Queue,Array,Stack,Linked List,C
20,Which city is known as the 'Big Apple'?,Los Angeles,Chicago,Miami,New York City,D

In [41]:
# Read Questions from above CSV
#Prepare 5-10 questions for a quiz
# A user will come and enter his/her name and take the quiz.
# One user cannot take quiz twice
# Save user score in a different csv named as student score
# if a student fail any question game will be end instantly

In [45]:
import random as r
randomnumberList = []
for i in range(10):
    while True:
        random10Numbers = r.randint(0,21)
        if random10Numbers not in randomnumberList:
            randomnumberList.append(random10Numbers)
            break
        else:
            continue

In [46]:
randomnumberList

[0, 20, 7, 11, 17, 6, 18, 1, 13, 15]